navikt/modiapersonoversikt-api

deploy/naiserator-q0.yaml, deploy/naiserator-q1.yaml, deploy/naiserator-q6.yaml, deploy/naiserator.yaml, kjerneinfo/kjerneinfo-consumer/src/main/java/no/nav/kjerneinfo/consumer/organisasjon/OrganisasjonV4ConsumerConfig.java, pom.xml, web/pom.xml, web/src/main/java/Main.java, web/src/test/java/MainTest.java
env-props kan lettere og raskere oppdateres når de ligger i yaml-filene
siden yaml-filen kan dyttes direkte til kubernetes (`kubctl apply`) uten at hele appen bygges på nytt.
=> [OPP-964] flyttet env-properties inn i nais.yaml

saksoversikt/pom.xml
https://github.com/advisories/GHSA-c9jj-3wvg-q65h
=> [KAIZEN-0] bump pdfbox pga sikkerhetshull

tilgangskontroll/src/main/java/no/nav/sbl/dialogarena/naudit/Audit.kt, tilgangskontroll/src/main/java/no/nav/sbl/dialogarena/naudit/AuditResources.kt
Sender alltid UPDATE/CREATE/DELETE, samt spesifike ressurser som
eksplisitt har `sendToArcsight`-flagget satt
=> [KAIZEN-0] minimerer data vi sender til arcsight

web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/oppgave/OppgaveController.kt
Hentet fra https://github.com/navikt/modiabrukerdialog/commit/e28a66437fc49e246952215d701d415741265fe0
=> [OPP-1116] fjerner tilgangsjekk på plukk for tilbakelegging.

consumer/src/main/resources/xml/fagomrade.xml, consumer/src/main/resources/xml/oppgaveT.xml, consumer/src/main/resources/xml/prioritetT.xml, consumer/src/main/resources/xml/underkategori.xml
med oppgavetyper, underkategori, fagområde og prioritet. Alfaversjon.
=> [OPP-1148]Aktivering av tema FRI 

consumer/src/main/resources/xml/underkategori.xml
flere gjelder-koder som skal vere gyldige
=> [OPP-1148] Utvidelse av innhold i gjelder-felt.

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/pdl/PdlSyntetiskFnrMapper.kt, consumer/src/main/resources/pdl/.graphqlconfig, consumer/src/main/resources/pdl/pdl-api-schema.graphql, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/enhet/EnhetController.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/enhet/EnhetControllerTest.kt
=> Prodsetting av Gsak-Kodeverk

api/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/api/domain/gsak/Sak.java, consumer/src/main/resources/xml/underkategori.xml
FRI er gyldig tema for journalføring og knytte til sak.
=> Prodsetting

pom.xml, web/pom.xml, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/config/JmxExporterConfig.kt, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/config/ModiaApplicationContext.java
spesielt hit/miss-raten til ehcache er interessant herifra
=> [KAIZEN-0] eksporterer jmx-metrics via prometheus

api/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/api/domain/gsak/Sak.java, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/saker/SakerServiceImpl.java, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/unleash/features.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/SakerServiceImplTest.java
introduserer `syntetisk` for ekstra-sikring på at ingen saker hentet fra
andre systemer kan ha mulighet til å bli spesialhåndtert i fremtiden.
=> [OPP-1159] legger til bidrag som sak

.nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais-q6.yml, .nais/nais.yml, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/config/ModiaApplicationContext.java
Vil sannsynligvis løse problemet med at cookien har blitt skrevet over av fpsak, men vil fortsatt gi støy i loggene våre da issoAuthenticatoren vil feile på validering av token
=> [KAIZEN-0] godta fpsak-frontend som audience

consumer/pom.xml, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/ApplicationFeilType.kt, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/HenvendelseUtsendingServiceImpl.java
FeilHåndtering for feil ved saktilknytting.
=> Opp 1172 henvendelse flere ganger (#75)

pom.xml
- oppsett for JUL-to-slf4j, slik at legacy-logging fra f.eks jersey fungerer korrekt
- backport/audience-check, sjekker jwt-audience før verifikasjon av tokens slik at "Token validation failed"-feilmeldingen ikke blir logget i tilfeller hvor audience ikke stemmer
=> [KAIZEN-0] bump common

api/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/api/domain/Oppgave.java, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/OppgaveBehandlingServiceImpl.java, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/oppgave/OppgaveControllerTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/service/PlukkOppgaveServiceImplTest.java
Mulig del av løsningen for å unngå at "Delvis svar" etc dukker opp for samtalereferate etc
=> [KAIZEN-0] legge til indikator på hvorvidt en oppgave kommer fra KNA/STO

api/src/main/resources/pdl/schema.graphql, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/config/service/ServiceConfig.java, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/OppgaveBehandlingServiceImpl.java, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/LeggTilbakeOppgaveIGsakDelegateTest.java, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/OppgaveBehandlingServiceImplTest.java, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/oppgave/OppgaveController.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/oppgave/OppgaveControllerTest.kt
Funksjonalitet for å legge tilbake allereie tildelte oppgaver som ein ikkje har tilgang til.
=> Opp 1237 tilgangskontrol på allereie tildelte oppgaver.

modia-felleskomponenter/src/main/java/no/nav/metrics/ProxyMetodeKall.java, modia-felleskomponenter/src/main/java/no/nav/metrics/TimerProxy.java
=> [KAIZEN-0] unwrapping av InvocationTargetException ved proxy-kall

web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/oppgave/OppgaveController.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/oppgave/OppgaveControllerTest.kt
KNA (Kontakt Nav)-oppgaver blir opprettet når bruker sender inn spørsmål, og er sånn sett en god indikator på at oppgaven kommer fra STO.
=> [OPP-1248] eksponere hvorvidt en oppgave er STO

.nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais-q6.yml, .nais/nais.yml, tilgangskontroll/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/tilgangskontroll/Tilgangskontroll.kt, web/pom.xml, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/aaputsending/AAPUtsendingController.kt, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/aaputsending/AAPUtsendingService.kt
For nå hardkodet til AAP-melding, men kan gjøres mer generisk over tid om ønskelig
=> [OPP-1256] legge tilendepunkt for masse utsending av melding

web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/enhet/EnhetController.kt
årsak til at arbeidsforderlig gjekk feil i ein god del tilfeller.
=> [OPP-1243]Endring av navn på parameter fra frontend

kjerneinfo/kontrakter-consumer/src/test/java/no/nav/kontrakter/consumer/fim/ytelseskontrakt/mock/YtelseskontraktMockFactory.java
=> [PROD] gjøre ytelsekontraktmock dato-uavhengig

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/OppgaveBehandlingServiceImpl.java
STO oppgaver tilgjengeliggjør legg-tilbakepanelet ved plukk, og styrer hvorvidt kontroll-spørsmåls etc skal vises
=> [KAIZEN-0] bedre utledning av hvorvidt en oppgave skal behandles som STOOppgave

sporsmalogsvar/src/main/java/no/nav/sbl/dialogarena/sporsmalogsvar/consumer/henvendelse/domain/Traad.java, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/dialog/DialogController.kt
Etter sammenslåing feilet den tidligere sjekken, da den eldste oppgaven hadde blitt ferdigstilt.
=> [KAIZEN-0] bedre sjekk om ferdigstilling kan gjøres

consumer/src/main/resources/xml/underkategori.xml
ein av mange oppdateringer som vil komme då me er litt på etterskudd med kodeverksoppdateringer fra gsak/gosys
=> [OPP-1306]  Ny underkategori for SYM, bestilling fra fagside

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/saker/kilder/GsakSaker.kt, consumer/src/main/resources/xml/underkategori.xml, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/saker/SakerServiceImplTest.java
WSSak er en java-klasse, og alle felter kan derfor være null uten at kotlin klager. e.g har typen (String!)
=> [PROD][FAGSYSTEM-149428] bedre null-håndtering av WSSak

api/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/api/domain/Temagruppe.java, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/OppgaveBehandlingServiceImpl.java
=> [OPP-1318] legge til ovrig som støtta for plukk

web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/aaputsending/AAPUtsendingService.kt
Må være tilstede for at soap-kall til aktørtjenesten etc skal fungere
=> [OPP-1330] sette callId i executor tråd

web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/aaputsending/AAPUtsendingService.kt
navn-objektet kan endres på, og det er derfor ønskelig å hente ut navn via motpartsident om mulig, og bare bruke navn som evt fallback
=> [PROD][KAIZEN-0] hente vergenavn om motpartsident finnes

web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/config/LoginContext.java
vi slutter dermed med å prøve å refreshe tokens fra veilarblogin
=> [OPP-1331] fjerne veilarblogin som godkjent audience

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/rest/RestOppgaveBehandlingServiceImpl.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
Vi har hatt en i overkant aggresiv tilgangskontroll når vi henter ut saksbehandlers tildelte oppgaver.
Denne listen kan inneholde alle mulige oppgaver, også typer som er tilknyttet orgnr og ikke aktorID.
I disse tilfellene slo vår tilgangskontroll inn, og regnet manglende aktorID som manglende tilgang.
Dette førte til at alle oppgaver uten aktorID automatisk ble fristilt fra saksbehandler om de åpnet modiapersonoversikt.
Endringen i denne PRen filtrerer bort alle oppgaver uten aktorID (og flytter sjekken for oppgaver uten henvendelse tilknyttning) når vi henter ut saksbehandlers tildelte oppgaver.
På den måten unngår vi å prosessere disse og dermed legger vi de ikke tilbake.
Dette betyr også at orgnr oppgaver ikke blir sendt til frontend-appen.
Dette regnes som ok siden disse tidligere …
=> [OPP-1308] slutte å fristille oppgaver tilknyttet orgnr

consumer/pom.xml, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/Utils.kt, consumer/src/main/resources/xml/oppgaveT.xml, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/UtilsTest.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/pdl/PdlOppslagServiceImplTest.kt, kjerneinfo/kjerneinfo-consumer/pom.xml, pom.xml, saksoversikt/pom.xml, sporsmalogsvar/pom.xml, tilgangskontroll/pom.xml, tilgangskontroll/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/tilgangskontroll/TilgangskontrollMock.kt, tilgangskontroll/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/tilgangskontroll/TilgangskontrollTest.kt, tilgangskontroll/src/test/java/no/nav/sbl/dialogarena/rsbac/RSBACTest.kt, web/pom.xml, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/PersonControllerIntTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/PersonControllerTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/enhet/EnhetControllerTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/kontaktinformasjon/KontaktinformasjonControllerTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/utbetaling/UtbetalingControllerTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/vergemal/VergemalControllerTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/ytelse/ForeldrepengerUttrekkTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/ytelse/PleiepengerUttrekkTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/ytelse/SykepengerUttrekkTest.kt
Forskjellen mellom de to er minimal, og det er derfor unødvendig å bruke begge to.
Mockk virker som en mer standard-løsning i kotlin-verden, så derfor falt valget på denne.
=> [PROD][KAIZEN-0] byttet nhaarman-mockito med mockk i tester som er skrevet i kotlin

api/src/main/resources/pdl/schema.graphql
PDL har gjort endringer i schema
=> [KAIZEN-0] Oppdaterer schema.graphql

web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/config/service/ServiceConfig.java, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/unleash/Feature.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
vært aktiv siden 03.06 uten noe feedback. Anser det derfor som greit å rydde opp i feature-toggles
=> [OPP-1103] fjerne featuretoggle for manuell overstyring

.github/workflows/deploy_branch.yml, .nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais.yml
wasapp-abac skal saneres, og det er ønskelig at alle selv tar ansvar for egen abac-instans.
ping og tilgang til aremark verifisert ok i q1
=> [OPP-1368] bytte abac-url

tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentPerson.graphql, tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/schema.graphql, web/src/test/java/no/nav/modiapersonoversikt/rest/PersonControllerIntTest.kt
=> [FAGSYSTEM-175801] hente ut info om historisk foreldreansvar for feilsøking

web/src/main/java/no/nav/modiapersonoversikt/service/oppfolgingsinfo/OppfolgingsinfoApiServiceImpl.java
Vi ser noen feil med tjenesten i produksjon (regional tilgang etc), så vi legger til litt mer feilhåndtering og logging for å undersøke saken
=> [KAIZEN-0] forbedre feilhåndtering og logging i OppfolgingApiImpl

web/src/main/java/no/nav/modiapersonoversikt/legacy/sak/service/saf/ExperimentSafService.kt
Vi ser noen feil med tjenesten i produksjon (regional tilgang etc), så vi legger til litt mer feilhåndtering og logging for å undersøke saken
=> [PROD][KAIZEN-0] forbedre feilhåndtering og logging i OppfolgingApiImpl

web/src/main/java/no/nav/modiapersonoversikt/rest/oppfolging/OppfolgingController.kt
ønsker i minst mulig grad å viderføre bruken av æøå i api/kode.
Avhengig av https://github.com/navikt/modiapersonoversikt/pull/1595 før denne kan gå til produksjon
=> [PROD][FAGSYSTEM-178851] fjerne ubrukte felter fra api

web/src/main/java/no/nav/modiapersonoversikt/rest/kontaktinformasjon/KontaktinformasjonController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/dkif/DkifServiceRestImpl.kt
logger feil og skaper støy. Setter raten til 0 mens vi feilsøker
=> [PROD][KAIZEN-0] sette dkif-eksperimentrate til 0

tjenestespesifikasjoner/saf-api/src/main/resources/saf/queries/hentbrukerssaker.graphql, web/src/main/java/no/nav/modiapersonoversikt/legacy/sak/service/saf/ExperimentSafService.kt, web/src/main/java/no/nav/modiapersonoversikt/legacy/sak/service/saf/SafGraphqlServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/legacy/sak/service/saf/SafService.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SafDebugController.kt
- [OPP-1387] sjekke behov for ekstra kall til pdl
- [OPP-1387] logge persondata feil til tjenestekallloggene
=> [PROD]fix/persondata

tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi.json, web/src/main/java/no/nav/modiapersonoversikt/config/service/DialogConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogMerkController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
all håndtering av sletting/sladding/kassering håndteres via salesforce
=> [KAIZEN-0] fjerne hastekassering api

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt
I frontend ønsker vi å vise om relasjoner har samme adresse som personen som søkes opp. Denne logikken gir mest mening å ha i backenden.
=> [OPP-1383] utvide foreldrebarnrelasjon med harSammeAdresse-felt

web/src/main/java/no/nav/modiapersonoversikt/rest/aaputsending/AAPUtsendingService.kt
- e26000051 [OPP-1399] oppdatert tekst for utsending AAP
=> [PROD] [OPP-1399] oppdatert tekst for utsending AAP

tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi.json, web/src/main/java/no/nav/modiapersonoversikt/rest/aaputsending/AAPUtsendingService.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletterTest.kt
dette kan mest sannsynligvis skje ved kassering, så har lagt til rapportering om vi oppdager null før kasseringstidspunktet.
=> [PROD][KAIZEN-0] gjøre fritekst nullable

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata-0.json
Vi ønsker å forbedre visningen til foreldreansvar med litt flere felter enn vi hadde før. Dette er primært ident.
=> [OPP-1383] utvide felter i foreldreansvar

web/src/main/java/no/nav/modiapersonoversikt/rest/aaputsending/AAPUtsendingService.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletterTest.kt
Vi ønsker å forbedre visningen til foreldreansvar med litt flere felter enn vi hadde før. Dette er primært ident.
=> [PROD][OPP-1383] utvide felter i foreldreansvar

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletterTest.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata-0.json
=> [OPP-1383] Legger til mapping på embete i vergemål og oppdaterer tester

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/OkHttpUtils.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/henvendelse/HenvendelseDialog.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
fjerner filtrering av ugyldige data, og måler nå også tiden vi bruker mot pdl for bedre måling mot pdl
=> [KAIZEN-0] utvided logging av sf meldinger

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/henvendelse/HenvendelseDialog.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
vi mister da verifikasjonssteget på dataene, og pdl-tiden blir nå logget av logginginterceptor
=> [PROD][KAIZEN-0] revert raw uthenting fra SF

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata-0.json
Vi trenger å eksponere GT til deler i frontenden. 
Da er det greit å sende denne med personobjektet, som også ble gjort fra TPS før.
=> [OPP-1383] legge til GT på persondata-objekt

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/OkHttpUtils.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/henvendelse/HenvendelseDialog.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
Vi trenger å eksponere GT til deler i frontenden. 
Da er det greit å sende denne med personobjektet, som også ble gjort fra TPS før.
=> [PROD][OPP-1383] legge til GT på persondata-objekt

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/saker/SakerServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/utils/ConcurrencyUtils.kt
- [KAIZEN-0] flytte inParallel utility til felles sted
- [KAIZEN-0] kalle journalføring og lukking i parallell
=> [KAIZEN-0] fix/sf concurrent

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/scientist/Scientist.kt, web/src/main/java/no/nav/modiapersonoversikt/utils/ConcurrencyUtils.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/scientist/ScientistTest.kt, web/src/test/java/no/nav/modiapersonoversikt/utils/ConcurrencyUtilsTest.kt
- [KAIZEN-0] lage tester for ConcurrencyUtils
- [KAIZEN-0] kjøre science-experiment i parallell med control
=> [KAIZEN-0] fix/parallel science

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/henvendelse/HenvendelseDialog.kt
- 7bf3f7d45 [KAIZEN-0] filtrere ut nye meldinger før sammenligning med SF
=> [PROD] [KAIZEN-0] filtrere ut nye meldinger før sammenligning med SF

web/src/main/java/no/nav/modiapersonoversikt/legacy/api/service/OppgaveBehandlingService.java, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt
Om siste melding i en meldingskjede er ett spørsmål er det mulig at dette har en tilknyttet oppgave. Om denne finnes vil den bli tilordnet veileder, og deretter lukket ved besvaring
=> [OPP-1378] søke etter STO-oppgave ved besvaring av meldingskjeder

web/src/main/java/no/nav/modiapersonoversikt/legacy/api/service/OppgaveBehandlingService.java, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/henvendelse/HenvendelseDialog.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt
Om siste melding i en meldingskjede er ett spørsmål er det mulig at dette har en tilknyttet oppgave. Om denne finnes vil den bli tilordnet veileder, og deretter lukket ved besvaring
=> [PROD][OPP-1378] søke etter STO-oppgave ved besvaring av meldingskjeder

web/src/main/java/no/nav/modiapersonoversikt/consumer/abac/Response.kt
policy fra abac ved deny pga fp3 har blitt endret, så legger til støtte for ny verdi.
=> [FAGSYSTEM-195951] oppdatere policy referanse fra abac

web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/unleash/Feature.kt
- c474fbe5d [OPP-1197] legge til eksperiment for personsok
=> [PROD] [OPP-1197] legge til eksperiment for personsok

web/src/main/java/no/nav/modiapersonoversikt/legacy/api/service/pdl/PdlOppslagService.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt
frontend håndterer ikke null-verdier for ident eller navn, så disse filtreres nå bort.
=> [OPP-1197] returnere søkresultat på forventet format

web/src/main/java/no/nav/modiapersonoversikt/config/service/DialogConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/henvendelse/HenvendelseDialog.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/unleash/Feature.kt
vi trenger nok ikke å ha denne på 100% mer, så flytter den ut til unleash for enklere å kontrollere fremover
=> [KAIZEN-0] bytte SF eksperitment til å bruke unleash

tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi.json, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
svar fra bruker vil da generere oppgave direkte til veileder/saksbehandler fremfor at oppgaven havner på enhetens benk
**DRAFT:** venter på api-spec endring for endelig navngivning av det nye feltet til SF
=> [NKS-1045] knytte tråd til ansatt om valgt

web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
siden vi manuelt bruker clienten ved patching av enkeltfelter så blir ikke standard valideringen fra generert kode kjørt.
kopiert ut hovedpoenge fra generert kode slik at feilmeldinger blir synelig for bruker
=> [KAIZEN-0] legge til håndtering av feil

.github/workflows/main.yml, .nais/nais-q0.yml, .nais/nais-q1.yml
Endring relatert til flytting av modiapersonoversikt-api til team namespace.
Endrer først bare namespace i preprod.
=> [OPP-1421] Endrer namespace

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt
pga at SF ikke utfører journalføring før tråd er lukket så ønsker vi at avslutting skjer så fort som mulig.
=> [KAIZEN-0] avslutte tråd ved utsending av svar

web/src/main/java/no/nav/modiapersonoversikt/legacy/api/service/OppgaveBehandlingService.java, web/src/main/java/no/nav/modiapersonoversikt/legacy/api/service/saker/GsakKodeverk.java, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/DialogOppgaveController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/enhet/EnhetController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/arbeidsfordeling/ArbeidsfordelingConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/arbeidsfordeling/ArbeidsfordelingService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/kodeverk/GsakKodeverkFraFil.java, web/src/main/java/no/nav/modiapersonoversikt/service/kodeverksmapper/domain/BehandlingExt.kt, web/src/main/java/no/nav/modiapersonoversikt/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, web/src/test/java/no/nav/modiapersonoversikt/service/arbeidsfordeling/ArbeidsfordelingServiceTest.java, web/src/test/java/no/nav/modiapersonoversikt/service/kodeverksmapper/domain/BehandlingExtTest.kt, web/src/test/java/no/nav/modiapersonoversikt/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
Her har V2-versjonene blitt renamet til original-navnet, men logikken er fortsatt den nye. Det kan se litt forvirrende ut i git-diffen 🤔
=> [OPP-1415][OPP-1417] Sanere logikk som brukte kodeverksmapperen

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/AdresseMappingTest.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata-0.json
gjøres slik at infomasjon om død partner kan vises
=> [PROD][FAGSYSTEM-210465] eksponere dodsdato i sivilstandrelasjoner

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt
feltene er hardkodet siden de ikke kan utledes fra dataene fra SF.
=> [KAIZEN-0] fjerne ubrukte felter

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/apis/DialogApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/EnhetligKodeverk.kt
for å på sikt kunne journalføre dialoger på flere temaet (som sf kan i dag) ønsker vi å vise alle journalposter som eksisterer i første omgang
=> [OPP-1043] eksponere alle journalposter for en tråd

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/apis/DialogApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/EnhetligKodeverk.kt
for å på sikt kunne journalføre dialoger på flere temaet (som sf kan i dag) ønsker vi å vise alle journalposter som eksisterer i første omgang
=> [PROD][OPP-1043] eksponere alle journalposter for en tråd

web/src/main/java/no/nav/modiapersonoversikt/consumer/ldap/LDAPServiceImpl.kt
vi kan ikke forvente at ting fra salesforce er sortert, og må derfor gjøre det selv
=> [PROD][KAIZEN-0] sortere alt fra henvendelse kronologisk

web/src/main/java/no/nav/modiapersonoversikt/rest/journalforing/SFJournalforing.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
for å sikre alle kall til SF blir nullstilt
=> [KAIZEN-0] sikre at BID saksid blir nullstilt

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/DialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/apis/DialogApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt
Vi ønsker å bruke tråden der meldingen blir lagt for å gjøre en sjekk på traadId i frontend, og må derfor returnere denne på post-kallene vi får i apiet.
=> [OPP-1407] sende tråden som respons ved dialog

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/DialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/apis/DialogApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/kodeverkproviders/enumkodeverk/Fagsystem.kt
Vi ønsker å bruke tråden der meldingen blir lagt for å gjøre en sjekk på traadId i frontend, og må derfor returnere denne på post-kallene vi får i apiet.
=> [PROD][OPP-1407] sende tråden som respons ved dialog

web/src/main/java/no/nav/modiapersonoversikt/rest/internal/InternalController.kt
- 8df9158d8 [KAIZEN-0] debug-endepunkt må logges inn
=> [PROD] [KAIZEN-0] debug-endepunkt må logges inn

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/AbacPolicies.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/Tilgangskontroll.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollContext.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollContextImpl.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollTest.kt
Per nå bare implementert generell tilgang til modia, og satt opp eksperiment for de andre kallene til abac
- [KAIZEN-0] slette ubrukt abac-policy
- [KAIZEN-0] slette ubrukt Tilgangskontroll policies
- [OPP-1442] sette opp eksperiment for alle kallene til abac
=> [OPP-1442] sette opp eksperiment for abac-policies

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt
frontend bruker nå feltet `journalposter` på tråd-nivå istedetfor
=> [OPP-1043] fjerne journalføringsfelter fra meldingDTO

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/Tilgangskontroll.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollContext.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollContextImpl.kt
- [OPP-1442] la til pensjons-roller for kode 6/7
- [OPP-1442] legge til policy for skjermet person
=> [OPP-1442] ekstra rolle for kode6/7 og policy for skjermet bruker

web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagService.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/person/PersonsokControllerTest.kt
Legger til searchHistorical. 
Vi kan nå styre om vi ønsker å ta med historisk når vi gjør søk.
=> [FAGSYSTEM-221145] Adressesøk - legger til mulighet til å styre om ønsker historisk i søk

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/scientist/Scientist.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/Tilgangskontroll.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollContext.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollContextImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/service/unleash/Feature.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/scientist/ScientistTest.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollTest.kt, web/src/test/java/no/nav/modiapersonoversikt/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
- [KAIZEN-0] legge til mulighet for å overstyre eksperiment rate
- [KAIZEN-0] eksponere unleash fra tilgangskontrollcontext
- [KAIZEN-0] sette opp eksperiment for alle tilgangspolicies
=> [KAIZEN-0] eksperiment for alle tilgangspolicies

web/src/main/java/no/nav/modiapersonoversikt/service/unleash/Feature.kt
- 82c8329b4 [KAIZEN-0] oppdatere featuretoggle navn med app-scope
=> [PROD] [KAIZEN-0] oppdatere featuretogglenavn med app-scope

tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/sokPerson.graphql, web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/person/PersonsokControllerTest.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.person.PersonsokControllerTest$PersonResponseMapper_should map pdl response when address(es) is invalid and filter them out-0.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.person.PersonsokControllerTest$PersonResponseMapper_should map pdl response without address-0.json
Ved å sjekke om vi har en gyldigtilOgMed som er før dagens dato så kan vi filtere bort i avansert søk adresser som ikke lenger er tilknyttet den personen
=> [FAGSYSTEM-221145] Legger til gyldigTilOgMed for å bruke til filtrering når adressesøk

web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/person/PersonsokControllerTest.kt
Forbedrer navnesøk slik at saksbehandler får mulighet til å avgrense søket hvis ønskelig
=> [OPP-1474] Erstatter fornavn og etternavn med navn

web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/person/PersonsokControllerTest.kt
Forbedrer adressesøk slik at saksbehandler får mulighet til å avgrense søket hvis ønskelig
=> [OPP-1470] Lager nytt endepunkt og api

pom.xml
Brukes ikke noe sted i koden, og skal fjernes fra henvendelse
=> [KAIZEN-0] fjern ubrukte dependencies

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt
Ønsker å vite hvilke kilde-typer vi kan forvente å få, så vi kan mappe om kodeverdiene til noe litt mer forståelig for brukerne våre
=> [OPP-1480] Legger til logging av kilde

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata-0.json
Blir færre varianter av ekvivalente kilder/systemKilder, og vi får også gjort flere kilder/systemKilder forståelige for bruker
=> [OPP-1482] Mapper om kjente kilder og systemKilder

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt
Ønsker å sammenligne hva vi får på registrertAv, systemKilde og kilde i forhold til om vi trenger registrertAv i frontend eller om vi kan bruke systemKilde
=> [KAIZEN-0] Legger til logging på PDL-KILDE

web/src/main/java/no/nav/modiapersonoversikt/consumer/brukernotifikasjon/BrukernotifikasjonService.kt
Produsent var ikkje srv men app-navn
=> [Kaizen-0]Endre fra servicebruker til app-navn

web/src/main/java/no/nav/modiapersonoversikt/consumer/brukernotifikasjon/BrukernotifikasjonClient.kt
Retting slik at vi viser alle notifikasjoner og ikkje kun aktive.
=> Feilretting hente ut alle notifikasjoner.

web/src/main/java/no/nav/modiapersonoversikt/rest/utbetaling/UtbetalingDTO.kt
- 156208a5e [KAIZEN-0] gjøre navn nullable
=> [PROD] [KAIZEN-0] gjøre navn nullable

web/src/main/java/no/nav/modiapersonoversikt/rest/utbetaling/UtbetalingController.kt
- 40d196e23 [KAIZEN-0] legge til felter uten æøå i gamle implementasjon av utbetaling
=> [PROD] [KAIZEN-0] felter uten æøå

tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentPersondata.graphql, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataResult.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/utbetaling/UtbetalingController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImpl.kt
henter ut gt i samme slenger som man henter persondata, og sparer derfor en round-trip til pdl
=> [PROD][KAIZEN-0] hente gt sammen med persondata

web/src/main/java/no/nav/modiapersonoversikt/consumer/brukernotifikasjon/Brukernotifikasjon.kt, web/src/test/java/no/nav/modiapersonoversikt/legacy/varsel/service/VarslerServiceImplTest.kt
Avhenger av en liten oppdatering i modia-eventer-api for å eksponere feltene.
=> [OPP-1478] legge til nye felter fra brukernotifikasjon

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata når person er dod-0.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata-0.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.TredjepartspersonMapperTest_skal mapper ulike adresse typer til internt domene-0.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.TredjepartspersonMapperTest_skal mapper ulike adresse typer til internt domene-1.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.TredjepartspersonMapperTest_skal mapper ulike adresse typer til internt domene-2.json
ønsker at coAdresse skal inkluderes for alle adresse-typer,
flytter det derfor ut i eget felt i `Adresse`.
Dette krever en oppdatering av visningen av adresser i frontend
=> [FAGSYSTEM-218607] endre coAdresse håndtering

web/src/main/java/no/nav/modiapersonoversikt/consumer/veilarboppfolging/ArbeidsrettetOppfolging.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/veilarboppfolging/ArbeidsrettetOppfolgingServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataResult.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataServiceImplTest.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataTestdata.kt, web/src/test/java/no/nav/modiapersonoversikt/service/oppfolgingsinfo/ArbeidsrettetOppfolgingImplTest.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata når person er dod-0.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata-0.json
- [FAGSYSTEM-241955] bytte endepunkt for henting av oppfolgingstatus
- [FAGSYSTEM-241955] eksponere manuell status fra veilarboppfolging
=> [FAGSYSTEM-241955] manuell oppfolging

tjenestespesifikasjoner/manuelle-fikser-for-api.main.kts, tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi-fixed.yaml
- 8c26760912 [FAGSYSTEM-244468] gjøre meldingsId nullable
=> [PROD] [FAGSYSTEM-244468] gjøre meldingsId nullable

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/apis/DialogApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
ønsker å bevege oss bort fra `mapOf(...)` for hva vi returnerer i api'et siden det gjør det vanskelig å vite hvilke felter som er nullable etc
=> [KAIZEN-0] eksperiment med typesatt TraadDTO

.nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais.yml
https://github.com/navikt/gandalf
=> [OPP-1466] bytte til nye STS for konverting til saml

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt
ikke noe behov for å parse det samme patternet 4 ganger for hver melding en bruker har
=> [KAIZEN-0] liten forbedring til ytelsen av mappingen som gjøres av henvendelser

tjenestespesifikasjoner/manuelle-fikser-for-api.main.kts, tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi-fixed.yaml, tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi.json, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
legger også til logging av feil når meldingsId er tomme fra Salesforce
=> [OPP-1501] oppdatert apispec for sladding av enkelt meldinger

tjenestespesifikasjoner/manuelle-fikser-for-api.main.kts, tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi-fixed.yaml, tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi.json, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/apis/DialogApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
legger også til logging av feil når meldingsId er tomme fra Salesforce
=> [PROD][OPP-1501] oppdatert apispec for sladding av enkelt meldinger

tjenestespesifikasjoner/ytelseskontrakt-v3-tjenestespesifikasjon/src/main/wsdl/tjenestespesifikasjon/no/nav/tjeneste/virksomhet/ytelseskontrakt/v3/informasjon/ytelseskontrakt/ytelseskontrakt.xsd, web/src/main/java/no/nav/modiapersonoversikt/rest/Utils.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/oppfolging/OppfolgingController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/ytelse/Common.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/ytelse/ForeldrepengerUttrekk.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/ytelse/PleiepengerUttrekk.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/ytelse/SykepengerUttrekk.kt
ikke nødvendig å reparse dato-format hver gang de brukes, så gjør nå denne jobbe up-front for bare java.time og joda-time
=> [PROD][KAIZEN-0] bytte til preparset DateFormatters

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/scientist/Scientist.kt, web/src/main/java/no/nav/modiapersonoversikt/utils/ConcurrencyUtils.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/scientist/ScientistTest.kt
gjøres slik at eksperiment skal kjøres uavhengig av resultatet til control.
=> [KAIZEN-0] kjører scientist control innenfor try-catch

web/src/main/java/no/nav/modiapersonoversikt/consumer/dkif/DigDirServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/scientist/Scientist.kt, web/src/main/java/no/nav/modiapersonoversikt/utils/ConcurrencyUtils.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/scientist/ScientistTest.kt
gjøres slik at eksperiment skal kjøres uavhengig av resultatet til control.
=> [PROD][KAIZEN-0] kjører scientist control innenfor try-catch

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/cache/CacheConfig.kt
- 0e758bd8ef [KAIZEN-0] eksplisitt be caffeine samle inn stats
=> [PROD] [KAIZEN-0] eksplisitt be caffeine samle inn stats

pom.xml, tjenestespesifikasjoner/pom.xml, web/pom.xml
kan på den måten slutte å bruke proxy-løsningen
=> [KAIZEN-0] henter modia-common og tjenestespesifikasjoner fra jitpack

pom.xml, web/src/main/java/no/nav/modiapersonoversikt/rest/Typeanalyzers.kt
- 6ff9bae8da [KAIZEN-0] bump common
=> [PROD] [KAIZEN-0] bump common

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/apis/DialogApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt
eneste identifiserte differenase er at `Veileder.navn` nå blir en del av responsen. Dette er ett nytt felt, som ikke vil påvirke frontend-løsningen
=> [KAIZEN-0] fjerne TraadDTO eksperiment

web/src/main/java/no/nav/modiapersonoversikt/consumer/nom/NomConfig.kt
- a12ad2e417 [KAIZEN-0] bytte tilbake til original cacheing for nom
=> [PROD] [KAIZEN-0] bytte tilbake til original cacheing for nom

web/src/main/java/no/nav/modiapersonoversikt/rest/TilgangController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/hode/HodeController.java
tilknyttet https://github.com/navikt/modiapersonoversikt/issues/641
- [KAIZEN-0] fjerne ubrukte felter fra response
- [KAIZEN-0] bruk valgtEnhet fra body
- [KAIZEN-0] eksplisitt kreve enhet som del av api'et
=> [KAIZEN-0] fjerne bruk av enhet fra cookie

web/src/main/resources/application.properties
Dette vil gi oss en kvantil tag på 95% som vi kan benytte oss av i Grafana.
=> [OPP-1508] Skru på kvantiler

web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerController.kt
Glemte å bruke gh-promote hehe
=> [PROD][OPP-1508] Skru på kvantiler

web/src/main/java/no/nav/modiapersonoversikt/config/MetricsConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/unleash/Feature.kt, web/src/main/java/no/nav/modiapersonoversikt/utils/MaskingUtils.kt, web/src/test/java/no/nav/modiapersonoversikt/utils/MaskingUtilsTest.kt
Legger til metricslistener til OkHttpClient.
Er avhengig av å teste dette i dev, for å se om initialiseringen skjer riktig i Spring. Har laget en toggle i unleash, hvor test identen min er aktivert. Kan eventuelt skru på denne for hele dev.
=> [OPP-1508] Add metricslistener to OkHttpClient

web/src/main/java/no/nav/modiapersonoversikt/utils/UrlMaskingUtils.kt, web/src/test/java/no/nav/modiapersonoversikt/utils/UrlMaskingUtilsTest.kt
- 25453df186 [KAIZEN-0] maskere GT og orgnr fra metrics
=> [PROD] [KAIZEN-0] maskere GT og orgnr fra metrics

web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerApiMapper.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerController.kt, web/src/main/java/no/nav/modiapersonoversikt/utils/ConvertionUtils.kt
ingen rapporterte feil i eksperimentet på lang tid, så fjerner den gamle koden.
og starter å ta ibruk den nye
=> [KAIZEN-0] fjerne sakercontroller eksperiment

web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt
- c80763ba79 [KAIZEN-0] fikse tracing av søkefelter
=> [PROD] [KAIZEN-0] fikse tracing av søkefelter

web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt
ønsker å bevege oss bort fra å returnere `Map<String, Any?>` slik at det blir enklere å holde oversikt på nullability i frontend etc
=> [PROD][KAIZEN-0] legge til type analyse av data fra oppfolgingscontorller

web/src/main/java/no/nav/modiapersonoversikt/consumer/arena/arenaSakVedtakService/ArenaSakVedtakServiceConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/arena/oppfolgingskontrakt/OppfolgingskontraktConfig.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/arena/ytelseskontrakt/YtelseskontraktConfig.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/brukervarsel/VarslingEndpointConfig.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/infotrygd/config/spring/foreldrepenger/ForeldrepengerConsumerConfig.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/infotrygd/config/spring/sykepenger/SykepengerConsumerConfig.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/infotrygd/consumer/pleiepenger/PleiepengerConsumerConfig.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/kontoregister/KontoregisterConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/krr/Krr.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/norg/NorgApi.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/sakogbehandling/SakOgBehandlingEndpointConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/skjermedePersoner/SkjermedePersonerApi.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/tps/PersonV3EndpointConfig.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/tps/PersonsokEndpointConfig.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/veilarboppfolging/ArbeidsrettetOppfolgingConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/ping/ConsumerPingable.java, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/ping/Pingable.java, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/ping/PingableWebService.java, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/ping/UnpingableWebService.java, web/src/main/java/no/nav/modiapersonoversikt/rest/NaisController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/EnhetligKodeverk.kt, web/src/main/java/no/nav/modiapersonoversikt/service/unleash/UnleashService.java, web/src/main/java/no/nav/modiapersonoversikt/service/utbetaling/UtbetalingService.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/ping/PingableWebServiceTest.java
- [KAIZEN-0] flytte Pingable interface til ping package
- [KAIZEN-0] slette ubrukt interface UnsafeConsumer
=> [KAIZEN-0] fix/ping location

web/src/main/java/no/nav/modiapersonoversikt/consumer/axsys/AxsysConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/ereg/OrganisasjonV1Client.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/nom/NomConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/baseurls/BaseUrlsController.kt
kallene til axsys og nom gjøres periodisk, men er likevel kjekke å ha i loggene
=> [PROD][KAIZEN-0] legge til logging for kall til axsys, nom og ereg

.nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais.yml, web/src/main/java/no/nav/modiapersonoversikt/rest/TilgangController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/VarslerController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/DialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/kontaktinformasjon/KontaktinformasjonController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/oppfolging/OppfolgingController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/oppgave/OppgaveController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/utbetaling/UtbetalingController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/ytelse/YtelseController.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/kontaktinformasjon/KontaktinformasjonControllerTest.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/utbetaling/UtbetalingControllerTest.kt
Reverts navikt/modiapersonoversikt-api#1142
=> [PROD][KAIZEN-0] Revert fjern feature toggle for fnr i path"

.nais/nais-q0.yml, web/src/main/java/no/nav/modiapersonoversikt/consumer/brukernotifikasjon/Brukernotifikasjon.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/brukernotifikasjon/BrukernotifikasjonClient.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/brukernotifikasjon/BrukernotifikasjonConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/brukernotifikasjon/BrukernotifikasjonService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/unleash/Feature.kt, web/src/main/java/no/nav/modiapersonoversikt/service/varsel/VarslerServiceConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/varsel/VarslerServiceImpl.kt, web/src/test/java/no/nav/modiapersonoversikt/service/varsel/VarslerServiceImplTest.kt
* [OPP-1598] Oppdatere tms-event api i personoversikt-api
=> [PROD][OPP-1598] Oppdatere tms-event api i personoversikt-api (#1154)

.nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais.yml
=> Oppdatere ereg endepunkt URLer

tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi.json
Det ser ut til at det er flere feil i schemaet. Det er lettest å reverte disse endringene fra #1193.
=> Manuelle fikser i SF Henvendelse openAPI schema

tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentPersondata.graphql, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata når person er dod-0.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata-0.json
tjenesteOppgaver er de tjenesteOppgavene som er knyttet til NAV som
tjenestevirksomhet i den ny definisjonen av vergemål fra
folkeregisteret.
=> [OPP-1627] Legg til tjenesteOppgaver på vergemål i persondata

web/src/main/java/no/nav/modiapersonoversikt/consumer/pdlPip/PdlPipApi.kt
=> Fiks feil i pdlPipApi hentIdenter

pom.xml, web/src/main/java/no/nav/modiapersonoversikt/consumer/pdlPip/PdlPipApi.kt
Feil i pdl-pip implementasjon med string likhet.
=> Fiks for manglende oppgaver 

web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImpl.kt
hentPersonBolk manglet behandlingsnummer og dette er påkrevd meget
snart.
=> Legge ved manglende behandlingsnummer på pdl req

web/src/main/java/no/nav/modiapersonoversikt/service/journalforingsaker/JournalforingSak.java
Se fagsystemsak. nEESSI har saker relatert til tema dagpenger.
=> Legg til NEESSI som godkjent fagsystem

.nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais.yml, tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentPersondata.graphql, tjenestespesifikasjoner/pdl-fullmakt-api/pom.xml, tjenestespesifikasjoner/pdl-fullmakt-api/src/main/resources/pdl-fullmakt-api/openapi.json, tjenestespesifikasjoner/pom.xml, web/pom.xml, web/src/main/java/no/nav/modiapersonoversikt/consumer/pdlFullmakt/PdlFullmaktApi.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/pdlFullmakt/PdlFullmaktConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/OkHttpUtils.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataResult.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataServiceImplTest.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataTestdata.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata når person er dod-0.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata-0.json
Bytt til pdl-fullmakt-api for å hente fullmakter, ettersom de nå er master.
=> Bruk PDL-fullmakt-api for fullmakter

.nais/nais.yml
- **Tillat trafikk fra prod-gcp**
- **Legg til prod-fss-pub ingress**
=> prod-fss-pub ingress

web/src/main/java/no/nav/modiapersonoversikt/consumer/arenainfotrygdproxy/ArenaInfotrygdApiConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/krr/KrrConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/krr/KrrServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/utbetaling/UtbetalingConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/veilarboppfolging/ArbeidsrettetOppfolgingConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/veilarboppfolging/ArbeidsrettetOppfolgingServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/OkHttpUtils.kt, web/src/main/java/no/nav/modiapersonoversikt/service/azure/AzureADService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/azure/AzureADServiceConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/saf/SafConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/saf/SafService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/unleash/Feature.kt, web/src/test/java/no/nav/modiapersonoversikt/service/krr/KrrServiceImplTest.kt, web/src/test/java/no/nav/modiapersonoversikt/service/oppfolgingsinfo/ArbeidsrettetOppfolgingImplTest.kt, web/src/test/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseServiceImplTest.kt, web/src/test/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseServiceIntegrationTest.kt
Reverts navikt/modiapersonoversikt-api#1335
=> Revert "[KAIZEN-0] feature toggle logging"

web/pom.xml, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/LoggingGraphqlClient.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/internal/InternalController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/service/saf/SafConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/saf/SafService.kt, web/src/test/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImplTest.kt
I håp om å få frem de manglende response loggene fra
hentBrukersDokumenter
=> Refactorer saf graphql client

tjenestespesifikasjoner/pom.xml, tjenestespesifikasjoner/tiltakspenger/pom.xml, tjenestespesifikasjoner/tiltakspenger/src/main/resources/tiltakspenger/openapi.yaml, web/.nais/dev.yml, web/.nais/prod.yml, web/pom.xml, web/src/main/java/no/nav/modiapersonoversikt/commondomain/FnrRequest.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/tiltakspenger/TiltakspengerConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/tiltakspenger/TiltakspengerService.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/naudit/AuditResources.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/ytelse/YtelseControllerV2.kt
Foreløpig lagt som et enkelt API under ytelser slik at man kan teste. Kan bli flyttet et annet sted i fremtiden.
=> Initiell implementasjon av tiltakspenger-datadeling

web/src/main/java/no/nav/modiapersonoversikt/commondomain/FnrRequest.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/skatteetaten/innkreving/SkatteetatenInnkrevingHttpClient.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/TilgangControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/VarslerControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/common/FnrRequest.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/DialogControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/journalforing/JournalforingControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/kontaktinformasjon/KontaktinformasjonControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/oppfolging/OppfolgingControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/oppgave/OppgaveControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/skatteetaten/innkreving/KravController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/skatteetaten/innkreving/json/KravdetaljerForPersonJsonRequest.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/skatteetaten/innkreving/json/KravdetaljerJsonResponse.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/utbetaling/UtbetalingControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/ytelse/YtelseControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/service/skatteetaten/innkreving/KravService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/skatteetaten/innkreving/KravdetaljerId.kt, web/src/main/java/no/nav/modiapersonoversikt/service/skatteetaten/innkreving/SkatteetatenInnkrevingClient.kt, web/src/test/java/no/nav/modiapersonoversikt/consumer/skatteetaten/innkreving/SkatteetatenInnkrevingHttpClientTest.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/skatteetaten/innkreving/KravControllerTest.kt, web/src/test/java/no/nav/modiapersonoversikt/service/skatteetaten/innkreving/KravServiceTest.kt
=> Legg til endepunkt for å hente kravdetaljer for en person

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt
Vi viser fullmektige for personen, men prøver å hente kontaktinfo for
fullmaktsgiver, som ikke gir mening. Dette fikser det så det er riktig
vei :)
=> Hent kontaktinfo for fullmektige tredjeparter

pom.xml
Reverts navikt/modiapersonoversikt-api#1404
=> Revert "Bump org.springframework.boot:spring-boot-starter-parent from 3.3.4 to 3.3.5"

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal filtrere ut egenAnsatt fra feiledeSystemer når veileder ikke har tilgang-0.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal ikke filtrere ut egenAnsatt fra feiledeSystemer når veileder har tilgang-0.json
Det gjør at enum verdiene kommer med i openAPI schemaet og vi kan få
bedre typer i frontenden autogenerert.
=> Bruk enum verdi i feilende systemer for persondata

web/src/main/java/no/nav/modiapersonoversikt/consumer/krr/KrrServiceImpl.kt, web/src/test/java/no/nav/modiapersonoversikt/service/krr/KrrServiceImplTest.kt, web/src/test/java/no/nav/modiapersonoversikt/utils/WireMockUtils.kt
Vi må bytte om til bulk endepunktet for å unngå å sende fnr i
url/headers.
=> Bruk KRR POST endepunkt istedenfor get /person

web/.nais/dev.yml
Nå skal SF journalføre i q2 og ikke q1, som skal gjøre det enklere for
oss å komme helt over på q2.
=> Bruk SAF q2

tjenestespesifikasjoner/krr-api/src/main/resources/krr/openapi.json, web/src/main/java/no/nav/modiapersonoversikt/consumer/krr/Krr.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/krr/KrrServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/kontaktinformasjon/KontaktinformasjonApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/kontaktinformasjon/KontaktinformasjonControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/TredjepartspersonMapper.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/kontaktinformasjon/KontaktinformasjonControllerTest.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataTestdata.kt, web/src/test/java/no/nav/modiapersonoversikt/service/krr/KrrServiceImplTest.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata når person er dod$web-0.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata$web-0.json
Tidspunkt for siste endring på reservasjonsstatus i KRR.
=> Legg til oppdateringstidspunkt for KRR-reservasjon

web/src/main/java/no/nav/modiapersonoversikt/consumer/veilarboppfolging/ArbeidsrettetOppfolging.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/veilarboppfolging/ArbeidsrettetOppfolgingServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/oppfolging/OppfolgingControllerV2.kt
Den kræsjer med Enhet i NorgDomain for openApi docs genereringen.
=> Endre navn på Enhet i oppfolging for konflikt

proxy/pom.xml, proxy/src/main/java/no/nav/modiapersonoversikt/infrastructure/CXFEvaluatorFilter.java, proxy/src/main/resources/logback.xml, web/src/main/resources/logback-stdout-fixed.xml, web/src/main/resources/logback.xml
- **Prøv å ikke bruke default logback config**
- **Bytt ut deprecated evaluationFilter for CXF**
=> logback fix

web/.nais/dev.yml, web/.nais/prod.yml
- **Legg til tilgangsmaskinen og test-api for tilgang**
- **Kjør tilgangsmaskinen som experiment**
- **Tilgang og nais config for tilgangsmaskinen**
=> Tilgangsmaskin nais config

web/src/main/java/no/nav/modiapersonoversikt/rest/oppfolging/OppfolgingControllerV2.kt
[KAIZEN-0] konflikt i data class navn VedtakDTO fra oppfolging og fra tiltakspenger
=> [KAIZEN-0] konflikt i data class navn VedtakDTO

pom.xml
Fikser kritisk security vulnerability i cxf dependencien ved å oppdatere cxf.
=> Oppdatere nav common versjon

tjenestespesifikasjoner/modia-soknadsstatus-api/pom.xml, tjenestespesifikasjoner/modia-soknadsstatus-api/src/main/resources/soknads-status/openapi.json, tjenestespesifikasjoner/pom.xml, web/.nais/dev.yml, web/.nais/prod.yml, web/pom.xml, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerApiMapper.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerControllerV2.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sakstema/FilterUtils.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sakstema/SakstemaServiceConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sakstema/SakstemaServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/service/soknadsstatus/Filter.kt, web/src/main/java/no/nav/modiapersonoversikt/service/soknadsstatus/Soknadsstatus.kt, web/src/main/java/no/nav/modiapersonoversikt/service/soknadsstatus/SoknadsstatusConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/soknadsstatus/SoknadsstatusSakstema.kt, web/src/main/java/no/nav/modiapersonoversikt/service/soknadsstatus/SoknadsstatusService.kt, web/src/test/java/no/nav/modiapersonoversikt/service/soknadsstatus/BehandlingMockUtils.kt, web/src/test/java/no/nav/modiapersonoversikt/service/soknadsstatus/FilterTest.kt, web/src/test/java/no/nav/modiapersonoversikt/service/soknadsstatus/SoknadsstatusServiceTest.kt
Reverts navikt/modiapersonoversikt-api#1580
=> Revert "[KAIZEN-0] Fjernet sokand-status api fra modiapersonoverskit-api."

pom.xml, proxy/.nais/nais-q1.yml, proxy/.nais/prod.yml, proxy/pom.xml, proxy/src/main/resources/logback-stdout-fixed.xml, web/.nais/dev.yml, web/.nais/prod.yml, web/src/main/resources/logback-stdout-fixed.xml
Har fulgt guiden https://docs.nais.io/observability/logging/how-to/team-logs
Har lagt til nødvendige dependencies, outbound access og appender til team logs.
Har oppdatert modia utils slik at tjenestekallogger sender begge plasse, så kan me fjerne secure logs etter kvart.
https://github.com/navikt/modia-common-utils/pull/177
=> Enable team logs

web/src/main/java/no/nav/modiapersonoversikt/service/dialog/DialogService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/dialog/DialogServiceImpl.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/kabac/policies/HenvendelseTilhorerBrukerPolicyTest.kt, web/src/test/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseServiceImplTest.kt
Testene bør gå gjennom med oppdatert open API schema etter salesforce release
=> AvsluttetAv og sattTilSladdingAv

pom.xml, proxy/.nais/nais-q1.yml, proxy/.nais/prod.yml, proxy/pom.xml, proxy/src/main/java/no/nav/modiapersonoversikt/infrastructure/naudit/Audit.kt, proxy/src/main/resources/logback-stdout-fixed.xml, web/.nais/dev.yml, web/.nais/prod.yml, web/pom.xml, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/naudit/Audit.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/Tilgangskontroll.kt, web/src/main/java/no/nav/modiapersonoversikt/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/service/persondata/PersondataFletter.kt, web/src/main/resources/logback-stdout-fixed.xml
Har lagt team logs appender for cxf logger
=> Legg til team logs

web/pom.xml
Reverts navikt/modiapersonoversikt-api#1669
=> Revert "Bump io.ktor:ktor-client-okhttp-jvm from 3.2.3 to 3.3.0"
