navikt/modiapersonoversikt-api

consumer/src/main/resources/cacheconfig.xml
Advice hadde navn `pesysService` som var samme som spring-bean fikk,
dette skapte en kollisjon som gjorde at injection av pesysService ikke
fungerte.
=> [KAIZEN-0] fikset advice-navngiving i spring for å unngå kollisjoner

pom.xml
time-modulen er på tur ut fra common, se PR: https://github.com/navikt/common-java-modules/pull/315
=> [KAIZEN-0] fjerner ubrukt avhengighet til common-time

.nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais-q6.yml, .nais/nais.yml
Hei
Vi har flyttet InnsynJournal_v2 tjenesten til dokarkiv på NAIS. Tjenesten er identisk og den har vært i bruk i produksjon siden 12. mars i år.
Vi ser at dere har URLer mot joark og ønsker få disse oppdatert. Vi kommer til å sanere tjenesten på joark så snart alle NAIS konsumenter har tatt i bruk ny url.
=> Endret InnsynJournal_v2 url fra joark (WAS) til dokarkiv (NAIS)

web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/person/PersonController.kt
`Fodselsnummer.java` i kjerneinfo inneholder spesialhåndtering av
situasjoner hvor fnr/dnr slutter med 00000 (og lignende).
I disse tilfellene blir alder-utregningen feil, så vi skjuler derfor
alder som en midlertidlig fiks her.
Årsaken til at utregning av alder fra fnr/dnr ikke fungerer når de
slutter med 00000 er at `fnr.substring(6,9)`, også kjent som
individnummer ikke kan utledes. Og sådan vet man ikke hvilket århundre
personen er født i.
=> [OPP-1179] vasker alder fra ugyldige fnr

tilgangskontroll/src/main/java/no/nav/sbl/dialogarena/naudit/ArchSightCEFLogger.kt, tilgangskontroll/src/main/java/no/nav/sbl/dialogarena/naudit/Audit.kt, tilgangskontroll/src/test/java/no/nav/sbl/dialogarena/naudit/ArchSightCEFLogger.kt
Endret på forespørsel fra ArchSight-folkene.
- endret `name` til `sproc`, `name` er ikke en godkjent CEF-key
- endret appname til `modia`, har tidligere vært `modia` så gjør ting lettere for de.
- endret logname til `personoversikt`, for å bevare informasjon om hvilket system det kommer fra
=> [KAIZEN-0] oppdaterte format på audit-logger

api/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/api/service/pdl/PdlOppslagService.kt, api/src/main/resources/pdl/queries/hentNavn.graphql, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/pdl/PdlOppslagServiceImpl.kt
Bruken er erstattet med bolk oppslag som gjør at det går færre kall til pdl
=> [KAIZEN-0] fjerne hentNavn-graphql-operasjon

kjerneinfo/sykmeldingsperioder-consumer/src/main/java/no/nav/sykmeldingsperioder/consumer/foreldrepenger/mapping/ForeldrepengerMapper.java
Boxed-versionen Boolean kan være satt til null, dette er ikke mulig for
den primitive typen boolean. Vi kan derfor få NullPointerException her om vi ikke sjekker
=> [KAIZEN-0] legge til null-sjekk før konvertering fra Boolean til boolean

api/pom.xml
Siden det var en litt annen struktur på den genererte koden fra openAPI så må vi manuelt legge til hvilke mapper vi vil at kotlin-kompilatoren skal ta hensyn til
=> [OPP-891] legge til generert kode i jar-filen til api-modul

api/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/api/service/OppgaveBehandlingService.java, sporsmalogsvar/src/main/java/no/nav/sbl/dialogarena/sporsmalogsvar/consumer/henvendelse/domain/Traad.java, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/dialog/DialogController.kt
Sjekket tidligere om det fantes en melding som referete til oppgaven, men ved manuell opprettelse av oppgave så vil ikke dette fungere.
Snur derfor om til å sjekke hvorvidt meldingen som blir referert til fra oppgaven finnes i tråden.
Hypotesen er at det er denne sjekken som gjør at disse feiler;
- FAGSYSTEM-142466
- FAGSYSTEM-142344
https://github.com/navikt/modiapersonoversikt-api/pull/210 utvider audit-loggeren slik at vi får bedre logger i disse situasjonene
=> [PROD][KAIZEN-0] flipper tråd-tilknyttning-sjekken

pom.xml
Ved kjøring lokalt brukes maven-central og ett mirror av ghpr hosted på gcloud. Dette gjøres slik at vi slipper å autentisere mot ghpr for henting av pakker.
maven-central er eksplisitt lagt til som første repo slik at henting av pakker prioriterer denne fremfor gcloud-mirror
Ved kjører på CI brukes en ghpr direkte da det her er enkelt å autentisere oss.
=> [KAIZEN-0] bruker maven-profiles for å styre aktive repositories

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/saker/kilder/GsakSaker.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/saker/SakerServiceImplTest.java
WSSak er en java-klasse, og alle felter kan derfor være null uten at kotlin klager. e.g har typen (String!)
=> [FAGSYSTEM-149428] bedre null-håndtering av WSSak

api/pom.xml
Mistenker at introduksjonen av private-pages i github har truffet pdl på en sånn måte at vi nå ikke får ut filen uten å sende med tokens for login.
For å fikse `dev` og byggene rundt omkring så disabler vi denne derfor for nå
=> [KAIZEN-0] disable sync av pdl.graphqls

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/OppgaveBehandlingServiceSwitcher.kt, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/saker/kilder/gsak/GsakSaker.kt, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/util/UnleashProxySwitcher.kt
Lagt til try-catch som fanger opp `InvocationTargetException` og pakker ut disse slik at man unngår `UndeclaredException`-feil og får penere stacktraces i loggene.
Trukket ut `InvocationHandler` til en egen klasse istedetfor en lambda. På den måten kommer man unna trøbbel med implisitt returns i kotlin.
Return-typen er også satt til `Any?` slik at proxyen støtter funksjoner som ikke returnerer noe eller returnerer `null`
=> [KAIZEN-0] fikse UnleashProxySwitcher etter merge med dev

web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/config/LoginContext.java
veilarblogin (`issoRefreshUrl`) kan ikke refreshe tokens utstedt til fpsak. Fjerner derfor konfigurasjonen for refresh-tokens fra fpsak-authenticatoren slik at vi ikke skaper støy i loggene.
=> [KAIZEN-0] fjerne refresh-config for fpsak authenticator

.nais/nais.yml, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/config/LoginContext.java
veilarblogin (issoRefreshUrl) kan ikke refreshe tokens utstedt til fpsak. Fjerner derfor konfigurasjonen for refresh-tokens fra fpsak-authenticatoren slik at vi ikke skaper støy i loggene.
=> [PROD] [KAIZEN-0] fjerne refresh-config for fpsak authenticator

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/rest/RestOppgaveBehandlingServiceImpl.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
I tilfeller hvor man oppretter en skjermet oppgave er dette fordi saksbehandler ikke har tilgang til brukeren. Vi kan derfor ikke bruke den vanlig `apiClient` siden dette vil forsøke å opprette oppgaven ved hjelp av saksbehandlers token.
Ved å bytte til systemApiClient brukes modia sitt systemToken som skal ha tilgang til å opprette oppgaver på alle brukere.
=> [KAIZEN-0] bruker system-klient for opprettelse av skjermet oppgave

api/src/main/resources/pdl/queries/hentPerson.graphql, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/pdl/PdlSyntetiskMapper.kt, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/person/PersonController.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/PersonControllerIntTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/PersonControllerTest.kt
Henter ut vergemål via `hentPerson` kallet til PDL, dette vil derfor ikke påvirke frontend siden det bare er snakk om å legge til nye felter i personResponsen og ikke en endring av eksisterende felter
=> [OPP-1153] hente ut vergemål fra pdl

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/rest/RestOppgaveBehandlingServiceImpl.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
`!=` i kotlin bruker "structural equality", e.g tilsvarende `!str.equals(str2)` i java, mens `!==` bruker `referential equality` som er tilsvarende `str1 != str2` i java.
Siden JVM'en forsøker å deduplisere strings, slik at man ikke har mange String-instanser med samme verdi så har testene fungert. Men oppdateringen til testen tvinger JVM'en til å lage to versjoner slik at vi får verifisert at sjekken bruker structural equality fremover.
=> [OPP-1308] fikse ident-sammenligning ved tilbakelegging

web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/aaputsending/AAPUtsendingController.kt, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/aaputsending/AAPUtsendingService.kt
ny utsending tar inn fnr-enhet-tuple, og sikrer slik at evt oppgaver havner til riktig enhet. Teksten er også oppdatert
=> [OPP-1330] oppdatere AAPUtsending for ny utsending

web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/person/PersonController.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/PersonControllerIntTest.kt
navn-objektet kan endres på, og det er derfor ønskelig å hente ut navn via motpartsident om mulig, og bare bruke navn som evt fallback. Ref. samtale i #mfn og nylig oppdatert pdl-doc;
> Informasjon knyttet til den som er verge eller fullmaktsmottaker.
Navn kan endre derfor bare bruke motpartsPersonident(fødselsnummer) og hente navn fra hentPerson graphQL query. Hvis det ligger ikke data på motpartsPersonident så kan bruke navn(hvis navn har data).
https://navikt.github.io/pdl/#_fremtidsfullmakt
=> [KAIZEN-0] hente vergenavn om motpartsident finnes

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/rest/RestOppgaveBehandlingServiceImpl.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
Gjøres for å gjøre rest-implementasjonen api-kompatible med tidligere soap-integrasjon.
I [OppgaveBehandlingServiceImpl.java::122](https://github.com/navikt/modiapersonoversikt-api/blob/dev/consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/OppgaveBehandlingServiceImpl.java#L122) filtrerer man ut alle oppgaver som har henvendelseId == null,
og på den måten vil tildelteOppgaver bare returnere oppgaver vi i modiapersonoversikt har ett forhold til.
=> [OPP-1308] filtrere bort oppgaver som ikke har henvendelse-tilknytning

api/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/api/service/saker/SakerService.kt, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/saker/SakerServiceImpl.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/saker/SakerServiceImplTest.kt, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/JournalforingController.java
Slettet depricated method i SakerService interface blir erstattet med hentSaker(fnr) som henter et samlet saker fra Arena, Sak Api, Bidrag, Pensjon kilder i tillegg med oppføring og Generell saker. Fikset test også.
=> Slette depricated method for henting av saker

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/rest/Utils.kt
plukk på øvrige ble lagt til i soap-implementasjonen 28.01.2021 ([se github blame her](https://github.com/navikt/modiapersonoversikt-api/blame/dev/consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/OppgaveBehandlingServiceImpl.java#L346))
men ikke oppdatert i rest-koden. 
resultatet er at plukk på OVRG prøver å plukke fra saksbehandlers-enhet benken (f.eks 4119) istedet for 4100 hvor oppgavene ligger
=> [OPP-1308] hente ovrg-oppgaver fra 4100

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/rest/RestOppgaveBehandlingServiceImpl.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
Viktig at systemApiClient blir brukt gjennom hele legg-tilbake-flyten,
siden vi her kan være i setting hvor saksbehandler ikke har tilgang til oppgaven.
Ett forsøk på å hente ut oppgaven via `apiClient` vil derfor feile, og da feiler tilbakeleggingen, og saksbehandler blir stuck med den oppgaven
=> [OPP-1308] bruke systemClient gjennom hele legg-tilbake flyten

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/rest/RestOppgaveBehandlingServiceImpl.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
Vi har hatt en i overkant aggresiv tilgangskontroll når vi henter ut saksbehandlers tildelte oppgaver.
Denne listen kan inneholde alle mulige oppgaver, også typer som er tilknyttet orgnr og ikke aktorID.
I disse tilfellene slo vår tilgangskontroll inn, og regnet manglende aktorID som manglende tilgang.
Dette førte til at alle oppgaver uten aktorID automatisk ble fristilt fra saksbehandler om de åpnet modiapersonoversikt.
Endringen i denne PRen filtrerer bort alle oppgaver uten aktorID (og flytter sjekken for oppgaver uten henvendelse tilknyttning) når vi henter ut saksbehandlers tildelte oppgaver.
På den måten unngår vi å prosessere disse og dermed legger vi de ikke tilbake.
Dette betyr også at orgnr oppgaver ikke blir sendt til frontend-appen.
Dette regnes som ok siden disse tidligere …
=> [PROD][OPP-1308] slutte å fristille oppgaver tilknyttet orgnr

api/pom.xml, api/src/main/resources/pdl/queries/hentPerson.graphql, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/person/DoedsboMapping.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/PersonControllerIntTest.kt
Nyeste versjon er 3.7.0, men denne medfører en del større endringer.
Bumper derfor i første omgang til 3.6.8 da denne fikser litt bugs rundt generering av kotlin-klasser.
Mest merkbart er de-duplisering av data-klasser med samme innhold.
F.eks ble det tidligere laget `Tolk` og `Tolk2`, som refererte til akkurat samme schema-element,
og hentet ut akkurat samme informasjon.
Disse klassene blir nå slått sammen, slik at det blir litt lettere å håndtere.
=> [KAIZEN-0] bumpe graphql-kotlin versjon

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
Noen saksbehandlere har veldig mange oppgaver tildelt seg selv, og om vi ikke spesifiserer hvor mange vi vil hente ut så får vi maksimalt 10 fra oppgave.
**Scenario;**
Saksbehandler har 15 tildelte oppgaver av ymse sort.
Saksbehandler ser en ny oppgave av type VURD_HENV, som hen kan besvare i modiapersonoversikt.
Saksbehandler tilordner seg oppgave i gosys/pesys, og klikker på "les/bevar i modia"
Modia laster inn, og henter ut saksbehandlers tildelte oppgaver. Denne listen vil da ikke inkludere den nylige tildelte oppgaver.
Og valget om å avslutte denne oppgaven blir derfor heller ikke tilgjengeliggjort for saksbehandler.
=> [FAGSYSTEM-163212] hente ut alle tildelte oppgaver for saksbehandler

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
Når vi bruker saksbehandlers jwt for kall til oppgave, så gjør oppgave tilgangskontroll mot ABAC.
Denne tilgangskontrollen er begrensen til å maks støtte 50 unike ressurser.
Hvis saksbehandler derfor har mer enn 50 åpne oppgaver risikerer vi derfor at kallet feiler.
=> [KAIZEN-0] sette limit for uthenting til 50

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/Utils.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
Oppgave støtter egentlig uthenting av 1000 oppgaver, men når man bruker usertoken så er dette begrenset til 50 pga kall til ABAC.
Det blir her satt til 49, og dette skyldes en off-by-one error i oppgave, e.g `antall < 50` vs `antall <= 50` sannsynligvis.
Per i dag, og for å være api-kompatible med soap-integrasjonen, trenger vi uansett å hente alle oppgavene.
Og vi ser spor av saksbehandlere som har mer enn 150 tildelte oppgaver.
Introduserer derfor paginering, for å sikre at vi får alle oppgave her.
=> [OPP-1308] legge til paginering ved uthenting av tildelte oppgaver

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/Utils.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
Oppgave støtter egentlig uthenting av 1000 oppgaver, men når man bruker usertoken så er dette begrenset til 50 pga kall til ABAC.
Det blir her satt til 49, og dette skyldes en off-by-one error i oppgave, e.g antall < 50 vs antall <= 50 sannsynligvis.
Per i dag, og for å være api-kompatible med soap-integrasjonen, trenger vi uansett å hente alle oppgavene.
Og vi ser spor av saksbehandlere som har mer enn 150 tildelte oppgaver.
Introduserer derfor paginering, for å sikre at vi får alle oppgave her.
=> [PROD][OPP-1308] legge til paginering ved uthenting av tildelte oppgaver

consumer/src/main/resources/xml/oppgaveT.xml
Vurder_konskevens og vurder_henvendelse er fra gammelt kodeverk satt til 0 dagers frist, SYK og SYM har fått endret dette i Gosys til 2 dager, men denne bestillinga har aldri komme til oss, det kan ligge flere slike avvik i perioden 2018-2020.
=> [OPP-1341] Oppdatering på SYM og SYK-kodeverk

consumer/pom.xml, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/pdl/PdlOppslagServiceImplTest.kt, kjerneinfo/kjerneinfo-consumer/pom.xml, pom.xml, saksoversikt/pom.xml, sporsmalogsvar/pom.xml, tilgangskontroll/pom.xml, tilgangskontroll/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/tilgangskontroll/TilgangskontrollMock.kt, tilgangskontroll/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/tilgangskontroll/TilgangskontrollTest.kt, tilgangskontroll/src/test/java/no/nav/sbl/dialogarena/rsbac/RSBACTest.kt, web/pom.xml, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/PersonControllerIntTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/PersonControllerTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/enhet/EnhetControllerTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/kontaktinformasjon/KontaktinformasjonControllerTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/utbetaling/UtbetalingControllerTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/vergemal/VergemalControllerTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/ytelse/ForeldrepengerUttrekkTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/ytelse/PleiepengerUttrekkTest.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/ytelse/SykepengerUttrekkTest.kt
Forskjellen mellom de to er minimal, og det er derfor unødvendig å bruke begge to.
Mockk virker som en mer standard-løsning i kotlin-verden, så derfor falt valget på denne.
=> [KAIZEN-0] byttet nhaarman-mockito med mockk i tester som er skrevet i kotlin

consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/Utils.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/UtilsTest.kt
`antallTreffTotalt` refererer til antall oppgaver før evt filtering basert på tilgangskontroll.
Vi kan derfor få tilbake en response uten data som sier `antalLTreffTotalt` og dermed havne i en evig løkke, siden vi forventer å få hentet ut mer informasjon en hva vi får fra oppgave.
Endringen her endrer på hvordan vi gjør pagineringen fra å være offset-orientert, til å være page-orientert.
Dvs at vi ikke lengre forsøker å holde styr på offset, men forholder oss til "pages" av "LIMIT"-størrelse.
Vi bruker deretter `antallTreffTotalt` til å kalkulere hvor mange pages vi må hente ut, og henter deretter ut alle pages.
Uavhengig av hva slags filtrering oppgave gjør så henter vi derfor ut all informasjonen som vi har lov til via dette kallet
=> [KAIZEN-0] hindre paginering i å hanve i evig løkke

api/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/api/service/OppgaveBehandlingService.java, consumer/pom.xml, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/oppgave/OppgaveController.kt, web/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/oppgave/OppgaveControllerTest.kt
oppgave gjør en del tilgangskontroll før oppgaven er returnert til oss.
Ifølge oppgave-teamet skal dette inkludere geografisk-tilgang, men for å være på den sikre siden logger vi nå hvilke oppgaver vi legger tilbake.
På den måten får vi ett bilde av hvorvidt vi trenger å gjøre ekstra tilgangskontroll på vår side.
**NB** Bygger videre på https://github.com/navikt/modiapersonoversikt-api/pull/322
=> [KAIZEN-0] logge warning om oppgaver blir lagt tilbake pga manglende tilgang

api/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/api/service/OppgaveBehandlingService.java, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/config/service/ServiceConfig.java, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/unleash/Feature.kt, consumer/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt, web/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/web/rest/dialog/DialogController.kt
Legger til sperre som hindrer at saksbehandlere "stjeler" hverandres oppgaver når de klikker på "Ny melding" i modia.
Det vil fortsatt være mulig å overstyre dette, men vil nå kreve ett ekstra felt for å gjøre dette.
=> [OPP-1103] legge til sperre for at saksbehandlere tar allerede tildelte oppgaver

saksoversikt/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/sak/service/saf/SafDokumentMapper.kt, saksoversikt/src/test/java/no/nav/sbl/dialogarena/modiabrukerdialog/sak/service/saf/SafDokumentMapperKtTest.kt
Samtalereferat blir nå vist som opprettet på dagens dato i modia selvom dette ikke er tilfelle. Dette skaper forvirring for veilederene, så endringene reverteres.
=> [REVERT-0][OPP-1001] Vises feil dato på samtalereferat

saksoversikt/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/sak/service/saf/SafDokumentMapper.kt
Denne oppgaven kunne ikke løses pga. manglende data, så har lagt til en kommentar i koden på dette slik at vi vet hvorfor valgt datotype blir brukt på notat.
=> [OPP-1001] Endrer dato i saksoversikten

.nais/nais.yml
Denne var tidligere en del av `dev`, men ble revertert siden abac-modia ikke var i prod og for fjerne blokkering av den PRen til prod.
=> [OPP-1368] endrer abac-url for prod

.nais/nais-q0.yml, .nais/nais-q1.yml, web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlSyntetiskMapper.kt
Forhåpentligvis stemmer disse miljøene bedre overens med TPS, slik at aktørid/fnr mapping stemmer med data fra henvendelse
=> [KAIZEN-0] bytte til pdl-q0/1 miljøene

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/naudit/AuditResources.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/TilgangController.kt
Gjort for å enklere kunne feilsøke probelmer i fremtiden.
Per idag stopper frontend opp om tilgangskontroll-sjekken sier at veileder ikke har tilgang. Det havner derfor veldig lite i loggen som kan forklare hvorfor.
=> [FAGSYSTEM-178062] legge til audit-logger for tilgangssjekken

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/scientist/Scientist.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/scientist/ScientistTest.kt
Så lenge resultatet fra eksperimentet serialiseres til samme json som kontrollen, så kan vi anta at ting er greit.
Det gir oss muligheten til å bruke `Scientist` når vi type-setter api-er som idag har veldig løse typer, e.g `Map<String, Any?>`
=> [KAIZEN-0] gjøre scientist istand til å sammenligne ulike datatyper

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/scientist/Scientist.kt, web/src/main/java/no/nav/modiapersonoversikt/service/oppfolgingsinfo/OppfolgingsinfoApiServiceImpl.java, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/scientist/ScientistTest.kt
Så lenge resultatet fra eksperimentet serialiseres til samme json som kontrollen, så kan vi anta at ting er greit.
Det gir oss muligheten til å bruke `Scientist` når vi type-setter api-er som idag har veldig løse typer, e.g `Map<String, Any?>`
=> [PROD][KAIZEN-0] gjøre scientist istand til å sammenligne ulike datatyper

web/src/main/java/no/nav/modiapersonoversikt/rest/oppfolging/OppfolgingController.kt
Pga tilgangskontroll i veilarboppfolging så kan man havne i en situasjon hvor vi ikke får hentet ut informasjon derifra selvom saksbehandler har tilgang.
For å håndtere dette på en bedre måte legger vi til nytt felt (`oppfolging`) som kan være `null`.
Om feltet er null så håndteres dette fra frontend-koden våres.
Når frontend-koden er oppdatert så kan vi rydde unna de gamle feltene.
=> [FAGSYSTEM-178851] legge til oppfolging-felt som kan være null

web/src/main/java/no/nav/modiapersonoversikt/rest/oppfolging/OppfolgingController.kt
ønsker i minst mulig grad å viderføre bruken av æøå i api/kode.
Avhengig av https://github.com/navikt/modiapersonoversikt/pull/1595 før denne kan gå til produksjon
=> [FAGSYSTEM-178851] fjerne ubrukte felter fra api

web/src/main/java/no/nav/modiapersonoversikt/consumer/kontrakter/consumer/fim/oppfolgingskontrakt/support/DefaultOppfolgingskontraktService.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/personsok/consumer/fim/personsok/support/DefaultPersonsokService.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/sykmeldingsperioder/consumer/foreldrepenger/DefaultForeldrepengerService.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/sykmeldingsperioder/consumer/pleiepenger/PleiepengerServiceImpl.java, web/src/main/java/no/nav/modiapersonoversikt/consumer/sykmeldingsperioder/consumer/sykepenger/DefaultSykepengerService.java, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/naudit/Audit.kt, web/src/main/java/no/nav/modiapersonoversikt/legacy/kjerneinfo/consumer/fim/person/support/HentPersonService.java, web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt
ved "denied"/"failed" situasjoner ville ikke standard identifikatorer bli logget. Dette er nå rettet opp slik at identifikatorerene alltid logges.
=> [KAIZEN-0] sikre bedre auditlogger

tjenestespesifikasjoner/kodeverk-api/pom.xml, tjenestespesifikasjoner/kodeverk-api/src/main/resources/kodeverk/openapi.json, tjenestespesifikasjoner/openapi-templates/libraries/jvm-okhttp/api.mustache, tjenestespesifikasjoner/openapi-templates/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache, tjenestespesifikasjoner/pom.xml, web/pom.xml, web/src/main/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/EnhetligKodeverk.kt, web/src/main/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/EnhetligKodeverkServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/KodeverkConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/KodeverkProviders.kt, web/src/test/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/EnhetligKodeverkServiceImplTest.kt
Denne PRen er todelt:
Først er det lagt opp til å integrere mot "Felles kodeverk" vha OpenAPI-specen deres, som skal erstatte dagens SOAP-løsning. Dette gjøres som et steg i prosessen når vi migrerer fra TPS til PDL.
Andre del implementerer en ny KoderverkService som kan ta inn nye kodeverk og hente ut disse fra forskjellige kilder
Endringen innebærer:
- Ny `pom.xml` for kodeverk
- Endring i `api.mustache` for å håndtere feil ved import av `parseDateToQueryString`
- Autogenerert openapi spec
- `EnhetligKodeverk` som holder på Service, Kilde og Kodeverk-klassen vår
- `EnhetligKodeverkServiceImp` som oppretter en cache som holder på kodeverk, og som oppdateres kl 01:00 hvert døgn
- Enum `KodeverkConfig` der man kan legge til flere typer kodeverk og funksjoner for å hente ut disse. Foreløpig …
=> [OPP-1384] åpne for integrasjon mot felleskodeverk

web/src/main/java/no/nav/modiapersonoversikt/config/JacksonConfig.java
tidligere gjort manuelt ved å konvertere til ulike string-format, eller i visse tilfeller magiske json-objekt.
ved å legge til `JavaTimeModule` så vil jackson få en forståelse av hvordan java.time.* skal serialiseres,
og disse kan da returneres fra kontrollere uten videre seremoni.
**Før:**
```
java.time.LocalDate.now() <-> {"year":2021,"month":"SEPTEMBER","monthValue":9,"dayOfMonth":16,"chronology":{"id":"ISO","calendarType":"iso8601"},"dayOfWeek":"THURSDAY","leapYear":false,"dayOfYear":259,"era":"CE"}
```
**Etter:**
```
java.time.LocalDate.now() <-> 2021-09-16
```
=> [KAIZEN-0] legge til jackson-mapping for java.time.*

web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImpl.kt
tidligere gjort manuelt ved å konvertere til ulike string-format, eller i visse tilfeller magiske json-objekt.
ved å legge til `JavaTimeModule` så vil jackson få en forståelse av hvordan java.time.* skal serialiseres,
og disse kan da returneres fra kontrollere uten videre seremoni.
**Før:**
```
java.time.LocalDate.now() <-> {"year":2021,"month":"SEPTEMBER","monthValue":9,"dayOfMonth":16,"chronology":{"id":"ISO","calendarType":"iso8601"},"dayOfWeek":"THURSDAY","leapYear":false,"dayOfYear":259,"era":"CE"}
```
**Etter:**
```
java.time.LocalDate.now() <-> 2021-09-16
```
=> [PROD][KAIZEN-0] legge til jackson-mapping for java.time.*

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/LoggingGraphqlClient.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/OkHttpUtils.kt, web/src/main/java/no/nav/modiapersonoversikt/legacy/kjerneinfo/consumer/organisasjon/OrganisasjonV1Client.kt, web/src/main/java/no/nav/modiapersonoversikt/legacy/sak/service/saf/SafGraphqlServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/aaputsending/AAPUtsendingService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/arbeidsfordeling/ArbeidsfordelingClient.kt, web/src/main/java/no/nav/modiapersonoversikt/service/dkif/DkifServiceRestImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/KodeverkProviders.kt, web/src/main/java/no/nav/modiapersonoversikt/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/service/saker/SakerServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
Hver gang vi skal hente callId så kjører vi samme kodesnutt. For å unngå duplikatkode så setter vi det ut i en felles global funksjon getCallId()
=> [KAIZEN-0] refaktorere uthenting av callId til en felles funksjon.

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/TredjepartspersonMapper.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.TredjepartspersonMapperTest_skal fjerne informasjon relatert til kode 6-7 ved manglende tilgang-0.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.TredjepartspersonMapperTest_skal fjerne informasjon relatert til kode 6-7 ved manglende tilgang-1.json, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.TredjepartspersonMapperTest_skal fjerne informasjon relatert til kode 6-7 ved manglende tilgang-2.json
Dersom man ikke har tilgang til personen, vil fnr bli satt til tom string. Det gjør at uthenting på fnr for tredjepartsperson senere vil matche på tom string. Det vil ikke gi noen informasjon, og dersom det finnes flere relasjoner man ikke har tilgang til vil alle disse overskrives.
=> [PROD][KAIZEN-0] fix: fjerne tilgangskontroll på ident-feltet i tredjepartsperson 

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt
Det hentes nå fra tredjepartsperson i tilfellet navnet vi får fra pdl på dødsbo er null så slår vi opp på fnr og henter navnet direkte fra pdl
=> [OPP-1383] Legger til navn på person som adressat

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/KodeverkConfig.kt
Gjør dette fordi vi da får hentet beskrivelsen fra felles kodeverk og vist denne i frontend, i stedet for kun å vise koden.
=> [OPP-1383] Endrer område til å være en kodebeskrivelse

tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentPersondata.graphql, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt
Ved noen tilfeller vil man både ha coAdressenavn og vegadresse. Logikken utelukket dette tilfellet, men vil nå lage et Adresse-objekt ved å slå sammen informasjon fra begge.
=> [PROD][OPP-1383] utvide kontaktadresse-mapping

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataResult.kt
Vi opplevde problemer med å sette bankkonto, selv om kallene til TPS fungerte slik de skulle.
For å kunne fange opp mapping-feil på vår side, lager vi `fold()` og oppdaterer `feilendeSystemer`.
=> [OPP-1383] Feilhåndtering persondata result

tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentPersondata.graphql, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt
Vi opplevde problemer med å sette bankkonto, selv om kallene til TPS fungerte slik de skulle.
For å kunne fange opp mapping-feil på vår side, lager vi `fold()` og oppdaterer `feilendeSystemer`.
En del av feltene vi fikk fra TPS for bankkonto var også tomme, så datamodellen måtte håndtere dette.
=> [PROD][OPP-1383] Feilhåndtering persondata result

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt
Vi ønsker ikke å vise bydelsnummer eller kommunenummer på bostedsadresse, da dette er duplikat informasjon i visittkortet og tallene gir lite mening alene.
Samtidig ønsker vi å bruke `coAdressenavn` da dette kan forekomme noen steder, og vi støttet det tidligere i TPS-visittkortet.
=> [PROD][OPP-1383] utvide bostedsadresse

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImpl.kt
Brukere med kode6 vil kun ha feltet gtType satt i PDL. Dette ville føre til at hentNavKontor returnerte null etter sjekk mot geografisk tilknytning før kallet til NORG. Nå garanterer vi at dersom man får en respons, så sender vi noe tilbake (gtType.toString()) og forhåpentligvis fungerer kallet til NORG.
=> [OPP-1383] unngå null-return på gt for kode6 brukere

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt
Brukere med kode6 vil kun ha feltet gtType satt i PDL. Dette ville føre til at hentNavKontor returnerte null etter sjekk mot geografisk tilknytning før kallet til NORG. 
Nå ønsker vi å unngå at dette skjer ved å sette GT til `""` dersom vi ikke får noe fra PDL, og så håndterer NORG diskresjonskode deretter. Dette ligner mer på logikken vi brukte for TPS også.
=> [PROD][OPP-1383] unngå null-return på gt for kode6 brukere

tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi.json, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
dette kan mest sannsynligvis skje ved kassering, så har lagt til rapportering om vi oppdager null før kasseringstidspunktet.
=> [KAIZEN-0] gjøre fritekst nullable

.github/workflows/main.yml
Om man lager flere commits (eller merger flere PRer) raskt til en dev/master så startes det flere workflows i parallell.
Endringen her gjør sånn at pågående workflows blir stoppet om man lager en ny commit.
På denne måten kan vi pushe commits i flere faser, og fortsatt ende opp med en enkelt deploy.
=> [KAIZEN-0] legge til concurrency kontroll på gh-workflow

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfTemagruppeTemaMapping.kt
mange temagrupper blir fjernet ved overgangen til SF, vi må derfor oppdatere mappingen til å håndtere dette.
I første omgang tar vi utgangspunkt i tidligere mapping, og gjør mindre tilpassninger slik at vi holder oss innenfor sf-begrensningene
=> [OPP-1378] legge til sf tema-temagruppe mapping

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/DialogOppgaveController.kt
frontend bruker `eldsteMelding(valgtTraad).id` som vil gi meldingsId istedetfor tradId.
Ved henting av data fra henvendelse vil disse være like per definisjon. Men denne samantikken endrer seg ved overgang til Salesforce
=> [OPP-1378] sikre at riktig id blir brukt ved oppgave opprettelse

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/OkHttpUtils.kt
Om content-length er 0 gir det ikke mening å forsøke å hente ut innholdet
=> [OPP-1378] forhindre at logging venter body når det ikke finnes noe der

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt
Vi hadde tidligere et filter på at vi bare søkte opp fnr, men vi ønsker også å støtte dnr. 
Endrer derfor også navnet på funksjonen.
=> [OPP-1383] tillate å bruke dnr og fnr

web/src/main/java/no/nav/modiapersonoversikt/consumer/abac/Response.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollTest.kt
Vi hadde tidligere et filter på at vi bare søkte opp fnr, men vi ønsker også å støtte dnr. 
Endrer derfor også navnet på funksjonen.
=> [PROD][OPP-1383] tillate å bruke dnr og fnr

web/src/main/java/no/nav/modiapersonoversikt/consumer/abac/Response.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollTest.kt
Dersom bruker bor i utlandet, vil vi få empty() på kallet til finnNavKontor(), og dette må håndteres i stedet for å kaste feil.
=> [PROD][OPP-1383] håndtere utenlandsk GT for nav-enhet

web/src/main/java/no/nav/modiapersonoversikt/consumer/abac/Response.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/TilgangskontrollTest.kt
Valuta og Landkode har ikke feltene kodeRef, men value.
Knyttet til feil i loggene:
Vi får følgende respons fra Soap: `<landkode>ESP</landkode>`
Og feilmelding: `bankkonto.bankkontoUtland.landkode.kodeRef must not be null`
Legger også til mock for BankKontoUtland, slik at vi ser at mappingen fungerer.
=> [PROD][OPP-1383] fikse feil på uthenting av bankkonto

web/src/main/java/no/nav/modiapersonoversikt/legacy/api/domain/saker/Sak.java
nytt fagsak system for enslig forsørger, sakene hentes fra `navikt/sak` så trenger bare oppdatering av whitelist
=> [KAIZEN-0] legge til enslig forsørger som godkjent fagsaksystem

tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentPersondata.graphql, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataTestdata.kt
Dette er i følge PDL lite brukt, og dette brukes til å finne ut hvor man skal sende post så det skal ikke være relevant i forhold til hvor noen bor.
=> [FAGSYSTEM-194911] Fjerner coAdressenavn fra bostedsadresse

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/scientist/Scientist.kt, web/src/main/java/no/nav/modiapersonoversikt/legacy/sak/service/saf/ExperimentSafService.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/henvendelse/HenvendelseDialog.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/kontaktinformasjon/KontaktinformasjonController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonController.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/scientist/ScientistTest.kt
ved å bruke `UnleashRate` kan man styre raten til ett eksperiment basert på en featuretoggle i unleash, og på denne måten få en raskere måte å endre raten på
=> [KAIZEN-0] legge til muligheten for å styre science vha unleash

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataController.kt
Vi ønsker å fjerne den gamle personControlleren, og flytter derfor hentIdenter og HentAktorId over til persondataController. Siden de gamle endepunktene brukes i frontend, må de dupliseres over til den nye urlen, fikses i frontend, og deretter slettes fra gamle personcontroller.
=> [OPP-1405] flytte hentIdenter og hentAktorId til person-v2

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataTestdata.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata-0.json
Det er en vurdering om vi heller skulle sortert på `sistEndret.tidspunkt`. Den har også klokkeslett.
Ved tilfeller der det er `gyldighetsperiode = null`, vil denne havne nederst.
=> [FAGSYSTEM-199029] sortere adresser basert på gyldigFOM

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/AdresseMappingTest.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletterTest.kt
årsskifte gjorde at alder-beregningen ble feil siden test-figuren hadde blitt eldre. Det er ikke ønskelig at tid skal få testene til å feile, så derfor brukes `Clock` for å "låse tiden"
=> [KAIZEN-0] bruke Clock slik at tester fungerer uavhengig av dato

web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt
logget tidligere objektet `NorskIdent` som skapte støy i tjenestekall-loggene
=> [KAIZEN-0] logge bare ident

web/src/main/java/no/nav/modiapersonoversikt/consumer/norg/NorgApi.kt, web/src/main/java/no/nav/modiapersonoversikt/utils/KotlinUtils.kt
Ikke numerisk GT tilsier at det er landkode pga utenlandsk GT og da har vi ingen enhet
=> [KAIZEN-0] ikke hente navkontor for utenlandsk gt

web/src/main/java/no/nav/modiapersonoversikt/legacy/api/service/pdl/PdlOppslagService.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImpl.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/person/PersonsokControllerTest.kt
Vi har informasjon om fornavn vs etternavn fra frontend-koden, og kan derfor gjøre søket litt bedre med å ikke blande disse sammen før vi sender det til PDL.
Vi kan med dette unngå at søk på Aremark Testfamilien returnerer folk med "***mark" til etternavn osv.
=> [OPP-1197] splitte navn-søk i egne felter

.nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais.yml
fjerner env-variabler som er ubrukt, og samtidig securitytoken/wsdlurl attributtene siden vi aldri har tatt ibruk disse etter migrering til nais
=> [KAIZEN-0] slette ubrukte felter fra nais-env-config

web/src/main/java/no/nav/modiapersonoversikt/legacy/api/service/pdl/PdlOppslagService.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/person/PersonsokControllerTest.kt
ved bruk av fuzzy (vs tidligere contains) får man for "aremark tesfamilien" bare en respons (som ved TPS-søk).
=> [OPP-1197] bytte tilbake til fritekst.navn og fuzzy-matching

web/src/test/java/no/nav/modiapersonoversikt/utils/WireMockUtils.kt
for å unngå trøbbel med eventuelle andre apper som måtte kjøre lokalt
=> [KAIZEN-0] kjøre wiremock tester på random porter

web/src/main/java/no/nav/modiapersonoversikt/rest/journalforing/SFJournalforing.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
Journalføring kan skje fra dialog-controller og journalforingscontroller, for å slippe å håndtere bid-hack begge steder flyttes det inn til SfHenvendelseService
=> [OPP-1378] flytte bid-hack håndtering for sf

tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi.json, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt
noen meldinger vil autogeneres av SF, men vi ønsker ikke at disse skal påvirke visningen i gosys.
Vi finner derfor siste meldinger som ikke har IdentType.SYSTEM og bruker verdiene derifra
=> [KAIZEN-0] håndtere system-ident fra sf

web/src/main/java/no/nav/modiapersonoversikt/rest/enhet/EnhetController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/arbeidsfordeling/ArbeidsfordelingService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/oppgavebehandling/RestOppgaveBehandlingServiceImpl.kt, web/src/main/java/no/nav/modiapersonoversikt/service/oppgavebehandling/Utils.kt, web/src/test/java/no/nav/modiapersonoversikt/service/oppgavebehandling/RestOppgaveBehandlingServiceImplTest.kt
Det er to måter å kalle på hentBehandledeEnheter - enten via leggTilbakeOppgaveIGsakV2 eller via endepunktet med samme navn. Førstnevnte håndterer allerede bruk av ny oppgave-struktur. For endepunktet løses dette med en ny V2.
=> [OPP-1417] erstatte kodeverksmapper for arbeidsfordeling

web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt, web/src/main/java/no/nav/modiapersonoversikt/utils/KotlinUtils.kt, web/src/test/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseServiceImplTest.kt
feil i Salesforce gjør at vi kan få tråder uten noen meldinger. For å hindre at disse får modia til å eksplodere så filtreres disse ut og vi logger feilen.
=> [PROD][KAIZEN-0] filtrere ut tråder uten meldinger

web/src/main/java/no/nav/modiapersonoversikt/legacy/sak/service/TilgangskontrollServiceImpl.java, web/src/test/java/no/nav/modiapersonoversikt/legacy/sak/service/TilgangskontrollServiceTest.java
Det begynner å komme bidrags dokumenter inn i joark, og vi ønsker nå åpne opp for å vise disse. Fjerner derfor den eksplisitte sperren, og lar SAF's tilgangskontroll håndtere tilgang til disse dokumentene.
=> [KAIZEN-0] tillate visning av bidragsdokumenter

.nais/nais.yml
Endring relatert til flytting av modiapersonoversikt-api til team namespace.
Må deploye PR https://github.com/navikt/vault-iac/pull/4322 først
=> [OPP-1432] Endrer namespace

web/src/main/java/no/nav/modiapersonoversikt/service/kodeverksmapper/domain/BehandlingExt.kt, web/src/test/java/no/nav/modiapersonoversikt/service/kodeverksmapper/domain/BehandlingExtTest.kt
i tilfeller hvor underkategori ikke er valgt vil vi få en tom streng, og vi vil da ha null-verdier for behandlignstema og behandlintstype
=> [KAIZEN-0] godta blank underkategori

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/kodeverksmapper/domain/BehandlingExt.kt, web/src/test/java/no/nav/modiapersonoversikt/service/kodeverksmapper/domain/BehandlingExtTest.kt
i tilfeller hvor underkategori ikke er valgt vil vi få en tom streng, og vi vil da ha null-verdier for behandlignstema og behandlintstype
=> [PROD][KAIZEN-0] godta blank underkategori

web/src/main/java/no/nav/modiapersonoversikt/rest/person/PersonsokController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/unleash/Feature.kt
for kontonummer brukes fortsatt TPS frem til ny løsning er på plass, men endepunkt og resterende kode for TPS-søket er nå fjernet
=> [KAIZEN-0] fjerne tps personsok

tjenestespesifikasjoner/manuelle-fikser-for-api.main.kts, tjenestespesifikasjoner/sf-henvendelse-api/src/main/resources/sf-henvendelse/openapi-fixed.yaml, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
legger til enum-verdi for chat fra SF slik at de kan starte med å sende det i responsen.
For nå blir alle chat-trådene filtrert ut slik at det ikke kan skal feil før vi ser at alt fungerer.
=> [KAIZEN-0] legge til rette for chat i modia

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt
sf endrer til å journalføre meldingskjeder fortløpende så lukking ved svar ikke lengre nødvendig.
Samtidig er det viktig at lukking skjer før journalføring ved utsending av infomelding for å sikre at dokumentet blir opprettet så fort som mulig, og at det ikke blir opprettet notat-dokument før lukking blir gjennomført.
=> [KAIZEN-0] endre lukke-logikk

web/src/main/java/no/nav/modiapersonoversikt/legacy/sak/service/saf/SafDokumentMapper.kt, web/src/main/java/no/nav/modiapersonoversikt/legacy/sak/service/saf/SafService.kt, web/src/test/java/no/nav/modiapersonoversikt/legacy/sak/service/saf/SafDokumentMapperTest.kt
finnes tilfeller i preprod hvor journalposter/dokumenter ikke har arkiv/sladdet variant. For å unngå at hele saksoversikten feiler så filtreres disse nå derfor ut
=> [KAIZEN-0] håndtere journalposter/dokumenter uten gyldig varianter

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/AdresseMappingTest.kt
Endret format til å matche visning i visning i pdl, e.g:
- \<postboks-eier>
- Postboks \<postboks-nummer>
- \<postnummer> \<poststed>
=> [FAGSYSTEM-209818] endre visning av postboks adresse

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/resources/snapshots/no.nav.modiapersonoversikt.rest.persondata.PersondataFletterTest_skal mappe data fra pdl til Persondata-0.json
gjøres slik at infomasjon om død partner kan vises
=> [FAGSYSTEM-210465] eksponere dodsdato i sivilstandrelasjoner

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataResult.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/AdresseMappingTest.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataTestdata.kt
gjøres lik at det er enklere å holde oversikt over hvilke verdier som kan komme fra endepunktet, og hva vi evt må håndtere i frontend
=> [KAIZEN-0] etablere enum for informasjonselementer i persondata

web/src/main/java/no/nav/modiapersonoversikt/consumer/skjermedePersoner/SkjermedePersonerConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataResult.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/AdresseMappingTest.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/persondata/PersondataTestdata.kt
gjøres lik at det er enklere å holde oversikt over hvilke verdier som kan komme fra endepunktet, og hva vi evt må håndtere i frontend
=> [PROD][KAIZEN-0] etablere enum for informasjonselementer i persondata

web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt
ser at disse eksisterer i preprod og vil sikre at disse ikke finnes i prod
=> [KAIZEN-0] legger til sjekk av sf-data for duplikate journalposter

web/src/main/java/no/nav/modiapersonoversikt/rest/internal/InternalController.kt
- har man tilgang til ett av de journalførte temaene så skal det være nok til å gi innsikt i meldingen
- Tråder bestående av flere samtalereferat vil ha duplikate innslag av journalposter siden i SF er ikke referatene sammenslåtte, og ved merging i API så blir ikke duplikate journalposter håndtert av dem.
=> [PROD][KAIZEN-0] endre tilgang for tema og fjerne duplikater

tjenestespesifikasjoner/norg-api/pom.xml, web/src/main/java/no/nav/modiapersonoversikt/consumer/norg/NorgApi.kt
Overordnet enhet kan ikke brukes da dette feltet er null i visse tilfeller, f.eks for enhet 0696 selvom enheten har en tilhørighet til en fylkes-enhet.
=> [KAIZEN-0] hente ut regional-enheter via norgs organisering api

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/kabac/impl/EvaluationContextImpl.kt
spesielt rolle-listen til veileder kan være stor, og er unødvendig å logge flere ganger siden den er cached innen for en evaluering
=> [KAIZEN-0] ikke printe verdier flere ganger i abac-rapport

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/kabac/Kabac.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/kabac/providers/BrukersAktorIdPip.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/kabac/providers/BrukersDiskresjonskodePip.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/kabac/providers/BrukersFnrPip.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/kabac/providers/NavIdentPip.kt
Hovedendringen er i `PIP::provider` hvor `TValue?` er endret til `TValue`.
Tidligere godtok pip'ene at man returnerte null selvom kontrakten til pip'en var å returnere en `TValue`, dette gjorde at policies og andre pip'er kunne havne i en situasjon hvor de fikk en nullpointerexception.
Endringen medfører nå at man må være eksplisitt om man ønsker å returnere null verdier, dette tvinger da policies til å håndtere disse fremover.
=> [KAIZEN-0] fjerne automatisk nullability fra kabac

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/kabac/Kabac.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/kabac/providers/BrukersAktorIdPip.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/kabac/providers/BrukersDiskresjonskodePip.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/kabac/providers/BrukersFnrPip.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/tilgangskontroll/kabac/providers/NavIdentPip.kt, web/src/main/java/no/nav/modiapersonoversikt/service/enhetligkodeverk/kodeverkproviders/enumkodeverk/Fagsystem.kt
Hovedendringen er i `PIP::provider` hvor `TValue?` er endret til `TValue`.
Tidligere godtok pip'ene at man returnerte null selvom kontrakten til pip'en var å returnere en `TValue`, dette gjorde at policies og andre pip'er kunne havne i en situasjon hvor de fikk en nullpointerexception.
Endringen medfører nå at man må være eksplisitt om man ønsker å returnere null verdier, dette tvinger da policies til å håndtere disse fremover.
=> [PROD][KAIZEN-0] fjerne automatisk nullability fra kabac 

web/src/main/java/no/nav/modiapersonoversikt/consumer/norg/NorgApi.kt, web/src/main/java/no/nav/modiapersonoversikt/service/arbeidsfordeling/ArbeidsfordelingConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/arbeidsfordeling/ArbeidsfordelingService.kt, web/src/test/java/no/nav/modiapersonoversikt/service/arbeidsfordeling/ArbeidsfordelingServiceTest.java
og bruke PdlOppslagService direkte i ArbeidsfordelingService, slik at man ikke trenger å gå via PersonDataService
=> [KAIZEN-0] bruke riktig diskresjonskode-format ved kall til norg

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt
- [KAIZEN-0] Endrer mapping på noen systemKilder basert på informasjon fra logging
Ved å se i loggen hvem som er registrertAv for de ulike systemKildene som forekommer, ser vi at det i disse tilfellene er NAV og bruker, så da endres mapping til de respektive verdiene bassert på informasjonen vi får fra hvem som har registrert endringen.
- [KAIZEN-0] Fjerner logging
Vi har nå fått informasjonen vi trenger for å avgjøre hvordan vi best kan mappe systemKilde i forhold til hvem det er registrertAv, så denne ekstra loggingen er ikke lenger nødvendig.
=> [KAIZEN-0] Endrer mapping av systemKilde

pom.xml
endrer på hvordan id_token cookie blir refreshet til å kopiere ut tidligere cookie sin domain/path
=> [KAIZEN-0] bump common-java-modules

tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentPersondata.graphql, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataResult.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagService.kt, web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImpl.kt
henter ut gt i samme slenger som man henter persondata, og sparer derfor en round-trip til pdl
=> [KAIZEN-0] hente gt sammen med persondata

tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentAdressebeskyttelse.graphql, tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentAktorid.graphql, tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentGeografiskTilknyttning.graphql, tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentIdenter.graphql, tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentPersondata.graphql, tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/hentTredjepartspersondata.graphql, tjenestespesifikasjoner/pdl-api/src/main/resources/pdl/queries/sokPerson.graphql, tjenestespesifikasjoner/saf-api/src/main/resources/saf/queries/hentBrukersDokumenter.graphql, tjenestespesifikasjoner/saf-api/src/main/resources/saf/queries/hentbrukerssaker.graphql, tjenestespesifikasjoner/saf-api/src/main/resources/saf/schema.graphql, web/src/main/java/no/nav/modiapersonoversikt/legacy/sak/service/saf/SafService.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SafDebugController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/saker/kilder/SafSaker.kt, web/src/test/java/no/nav/modiapersonoversikt/service/saker/SakerServiceImplTest.kt
gjør det litt enklere å identifisere graphql-requester i loggene, siden operationname er noe vi logger for requesten
=> [KAIZEN-0] legge til operationname for graphql spørringer

.nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais.yml
Nye dev-ingress har ikke et klart skille på q1/q2 i følge utviklerne.
=> [KAIZEN-0] oppdatere veilarboppfolging urler

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/TjenestekallLogger.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/LoggingGraphqlClient.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/OkHttpUtils.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/naudit/Audit.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/scientist/Scientist.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/utbetaling/UtbetalingController.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/scientist/ScientistTest.kt
ved bruk av fields og tags kan man styre hvilke verdier som blir lagt inn i "message" i loggen, og hvilke felter som blir søkbare/indekserte av kibana
Legger til felles marker felt til de fleste kall til tjenestekallloggen `logtype` som gjør det enkelt å finne igjen logglinjer fra en spesifik komponent, f.eks audit eller scientist
=> [KAIZEN-0] utvidet funksjonalitet til tjenestekall logger

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/TjenestekallLogger.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/LoggingGraphqlClient.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/OkHttpUtils.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/naudit/Audit.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/scientist/Scientist.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/utbetaling/UtbetalingController.kt, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/scientist/ScientistTest.kt
ved bruk av fields og tags kan man styre hvilke verdier som blir lagt inn i "message" i loggen, og hvilke felter som blir søkbare/indekserte av kibana
Legger til felles marker felt til de fleste kall til tjenestekallloggen `logtype` som gjør det enkelt å finne igjen logglinjer fra en spesifik komponent, f.eks audit eller scientist
=> [PROD][KAIZEN-0] utvidet funksjonalitet til tjenestekall logger

web/src/main/resources/cacheconfig.xml, web/src/test/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceCacheTest.java
ved feil mot PDL returneres `null`, som default vil ikke `Caffeine` cache null-verdier. Men spring-cache ser ut til å få det til likevel (╯°□°)╯︵ ┻━┻
må derfor legge til en manuell sjekk vha ett spel-uttrykk
=> [KAIZEN-0] unngå å cache null-verdier fra pdl

web/src/main/java/no/nav/modiapersonoversikt/rest/Utils.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/oppfolging/OppfolgingController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/ytelse/Common.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/ytelse/ForeldrepengerUttrekk.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/ytelse/PleiepengerUttrekk.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/ytelse/SykepengerUttrekk.kt
ikke nødvendig å reparse dato-format hver gang de brukes, så gjør nå denne jobbe up-front for bare java.time og joda-time
=> [KAIZEN-0] bytte til preparset DateFormatters

web/src/main/java/no/nav/modiapersonoversikt/utils/ConcurrencyUtils.kt, web/src/test/java/no/nav/modiapersonoversikt/utils/ConcurrencyUtilsTest.kt
Om deler av koden kjøres i parallell så må vi passe på at threadlocals blir kopiert over til de nye trådene slik at eventuelle kall til tjenester blir kjørt med riktig auth-headers etc
=> [KAIZEN-0] legge til AuthHeaderCapture til thread-swapper

web/src/main/java/no/nav/modiapersonoversikt/consumer/dkif/DkifConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/kontaktinformasjon/KontaktinformasjonController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataConfig.kt, web/src/test/java/no/nav/modiapersonoversikt/rest/kontaktinformasjon/KontaktinformasjonControllerTest.kt
gjør det enklere å gjenbruke på tvers av applikasjonen, og blir nå automatisk også brukt av PersondataService
=> [KAIZEN-0] flytte dkif-experiment til service-nivå

web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/ansattservice/AnsattService.kt, web/src/test/java/no/nav/modiapersonoversikt/service/ansattservice/AnsattServiceImplTest.kt
ved uthenting av meldinger må mange veiledernavn hentes ut,
dette gjøres mer effektivt vha nom bolk-oppslag
=> [KAIZEN-0] bytte til bolk-oppslag mot nom

web/src/main/java/no/nav/modiapersonoversikt/rest/Typeanalyzers.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/internal/InternalController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerController.kt
det er ønskelig med typesikre (e.g ikke `Map<String, Any>`) respons-typer fra alle endepunkt. Typeanalyzer finner ut av hva disse typene kan være
=> [KAIZEN-0] legge til type introspeksjon for saker

web/src/main/java/no/nav/modiapersonoversikt/consumer/nom/NomConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/nom/NullCachingNomClient.kt, web/src/main/java/no/nav/modiapersonoversikt/infrastructure/cache/CacheConfig.kt, web/src/test/java/no/nav/modiapersonoversikt/consumer/nom/NullCachingNomClientTest.kt
Fungerer veldig likt som `CachedNomClient`, men underliggende cache er basert på `Optional<VeilederNavn>` slik at også null-verdier kan caches
Null-verdier er relevant her fordi Nom ikke holder på informasjon om utløpte identer, e.g folk som har sluttet etc
=> [KAIZEN-0] bruke custom nom cache

web/src/main/java/no/nav/modiapersonoversikt/consumer/nom/NomConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/consumer/nom/NullCachingNomClient.kt, web/src/test/java/no/nav/modiapersonoversikt/consumer/nom/NullCachingNomClientTest.kt
NomClientImpl vil aldri returnere `null` eller ha `null` elementer i listen.
Skrevet om NullCachingNomClient til å følge samme mønster med exceptions og fjerner null-elementer i listen om informasjon ikke finnes
=> [KAIZEN-0] sikre at caching wrapper følger samme api som underliggende tjeneste

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/naudit/AuditResources.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/hode/HodeController.java, web/src/test/java/no/nav/modiapersonoversikt/infrastructure/naudit/ArchSightCEFLoggerTest.kt
endepunktet ble tidligere brukt for å sette valgtEnhet som cookie. Men dette er nå løst vha localStorage og modiacontextholder.
=> [KAIZEN-0] fjerne ubrukt endepunkt

.nais/nais.yml
https://github.com/navikt/tms-event-api/blob/main/nais/prod-gcp/nais.yaml#L29
=> [KAIZEN-0] bytte til riktig url for tms-event-api i produksjon

web/src/main/java/no/nav/modiapersonoversikt/Main.java, web/src/main/java/no/nav/modiapersonoversikt/config/MetricsConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/unleash/Feature.kt
[OPP-1508] Refaktorere hvordan RestClient blir initialisert med metrikklytter
Revert "[OPP-1508] Add metricslistener to OkHttpClient"
Revert "Revert "[OPP-1508] Add metricslistener to OkHttpClient""
This reverts commit d116b72d74f53a947d0088804f8fe457ca5b8fbe.
=> [OPP-1508] Refaktorere hvordan RestClient blir initialisert med metrikklytter

web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerApiMapper.kt, web/src/main/java/no/nav/modiapersonoversikt/utils/ConvertionUtils.kt
Ønsker å bruke ISO8601 når datoer sendes via json fremfor ett eget custom format.
La derfor til "V2" av alle datoer på nytt format slik at frontend kan oppdateres ved en passende anledning.
Det er ikke ønskelig med "æøå" i koden, felter med ett av disse tegnene er duplisert med følgende mapping:
æ -> e
ø -> o
å -> a
=> [KAIZEN-0] state på rydding i sakerapi

web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerApiMapper.kt
frontend må bytte tilbake til å bruke de originale variabel-navnene, og deretter kan V2-feltene slettes
=> [KAIZEN-0] fjerne legacy dato-format fra saks api

web/src/main/java/no/nav/modiapersonoversikt/rest/Typeanalyzers.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/oppfolging/OppfolgingController.kt
ønsker å bevege oss bort fra å returnere `Map<String, Any?>` slik at det blir enklere å holde oversikt på nullability i frontend etc
=> [KAIZEN-0] legge til type analyse av data fra oppfolgingscontorller

web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerApi.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/saker/SakerApiMapper.kt
frontend bruker ikke lengre V2-variantene etter https://github.com/navikt/modiapersonoversikt/pull/2012
=> [KAIZEN-0] fjerne midlertidig overgangs variabler

linting.sh
bash ligger ikke nødvendigvis på samme sted på ulike maskiner eller OS,
ved å bruke /usr/bin/env så brukes første "bash" program som finnes i $PATH og det burde derfor fungere på alle *nix OS
=> [KAIZEN-0] fikse linting script

.nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais.yml, README.md, web/src/main/java/no/nav/modiapersonoversikt/rest/baseurls/BaseUrlsController.kt
- [KAIZEN-0] forenkle baseurls endepunkt
- [KAIZEN-0] fjerne ubrukte miljøvariebler fra nais.yml
Følgende variabler er fjernet siden de ikke er ibruk i kodebasen: 
- SERVER_AKTIVITETSPLAN_URL
- SERVER_ARENA_URL
- SERVER_GOSYS_URL
- SERVER_PESYS_URL
- SERVER_VEILARBPORTEFOLJEFLATEFS_URL
- SERVER_AAREG_URL
- TJENESTER_URL
- VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_ENDPOINTURL
- DKIF_REST_URL
- PREFETCH_NORG_ANSATTLISTE_SCHEDULE
- FJERN_SOKNADER_FOR_DATO
- HASTEKASSERING_TILGANG
- DITTNAV_EVENTER_MODIA_URL
=> [KAIZEN-0] fix/mini env

.github/workflows/topic.yml, .nais/nais-q0.yml, .nais/nais-q1.yml, .nais/nais.yml, .nais/topics/dev.json, .nais/topics/henvendelse-oppdatering-melding.yml, .nais/topics/prod.json, pom.xml, web/pom.xml, web/src/main/java/no/nav/modiapersonoversikt/kafka/CommonKafkaProps.kt, web/src/main/java/no/nav/modiapersonoversikt/kafka/HenvendelseKafkaConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/kafka/HenvendelseProducer.kt, web/src/main/java/no/nav/modiapersonoversikt/kafka/KafkaPersonoversiktProducer.kt, web/src/main/java/no/nav/modiapersonoversikt/kafka/KafkaSecurityConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/kafka/dto/HenvendelseKafkaDTO.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/DialogConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/dialog/salesforce/SfLegacyDialogController.kt, web/src/main/java/no/nav/modiapersonoversikt/service/unleash/Feature.kt, web/src/test/java/no/nav/modiapersonoversikt/kafka/HenvendelseProducerTest.kt
Team flex ønsker informasjon om antall meldinger som sendes på temaet SYK. Denne PRen legger til kafka producer som sender alle henvendelser som melding på kafka topic personoversikt.henvendelse-oppdatering-melding. I framtiden kan det være at flere tema blir sendt på dette temaet, så da er konsumentene selv ansvarlig for å filtrere ut meldinger som er relevante.
=> [OPP-1566] Legge til kafka, sende henvendelse oppdateringer

web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImpl.kt, web/src/test/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImplTest.kt
For å unngå at man i KABAC kan få tilgang til skjermede personer om PDL responderer med valideringsfeil. Koden tok tidligere ikke hensyn til dette, og tolket det som at det ikke fantes adressebeskyttelse på disse
=> [KAIZEN-0] Kaste feil på PDL kall

web/src/main/java/no/nav/modiapersonoversikt/Main.java
`modulesToInstall` legger til i _tillegg_ til spring auto-configuration,
mens `modules` overskriver...
=> Ikke overskriv spring config

web/src/main/java/no/nav/modiapersonoversikt/infrastructure/http/OkHttpUtils.kt
Vi har ikke kontroll over størrelsen og vi kan logge for mye
informasjon, og potensielt informasjon som ikke trengs/skal logges.
=> Ikke logg repoonse body by default.

web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImpl.kt, web/src/test/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImplTest.kt
Vi får ikke bruke user tokens på denne querien, da PDL ikke gjør
tilgangskontroll. Denne commiten endrer tilbake til å bruke systemtoken
slik at tredjepartspersondata fungerer igjen.
=> Bruk systemtoken på hentTredjepartspersondata

web/src/main/java/no/nav/modiapersonoversikt/consumer/norg/NorgConfig.kt
Kallene til Norg2 tar litt lenger tid, og med 5 sek timeout closer vi
connections før norg rekker å svare.
=> Øke timeout til Norg2 fra 5sek til 30sek

tjenestespesifikasjoner/saf-api/src/main/resources/saf/schema.graphql, web/src/main/java/no/nav/modiapersonoversikt/service/journalforingsaker/JournalforingSak.java, web/src/test/java/no/nav/modiapersonoversikt/rest/journalforing/JournalforingControllerTest.kt, web/src/test/java/no/nav/modiapersonoversikt/service/journalforingsaker/SakerServiceImplTest.kt
En eller annen endring, antakeligvis kotlin compiler eller jackson, har gjort at denne getteren ikke ble kalt og serialisert. Problemet manifesterte seg kun når man bygger jaren, og dukket ikke opp i tester, men å slenge på en `JsonGetter` annotation fikser problemet :shrug:
=> [PROD] Fiks for manglende saksId på saker

web/src/main/java/no/nav/modiapersonoversikt/consumer/arenainfotrygdproxy/ArenaInfotrygdApiConfig.kt, web/src/main/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseService.kt, web/src/test/java/no/nav/modiapersonoversikt/service/sfhenvendelse/SfHenvendelseServiceImplTest.kt
Ikke skjul henvendelser som mangler temagruppe. Det er noe feil hos SF
som gjør at vi får flere henvendelser uten temagruppe, som da ikke vises
til veiledere. Det er bedre at vi viser meldingene selv om de mangler
temagruppe slik at de ikke tror at bruker ikke har svart dem når de
forventer svar.
=> Håndter henvendelser uten temagruppe bedre

web/src/main/java/no/nav/modiapersonoversikt/service/azure/AzureADService.kt
Antakeligvis er det en default page size på 100 (dette står ikke nevnt i
dokumentasjonen, men trail and error viser at det nok stemmer) som gjør
at visse identer som har flere enn disse kan risikere å ikke gå gjennom
access control siden vi ikke mottar gruppene som er paginerte.
=> Sett page size til 200 fra ms graph

web/src/main/java/no/nav/modiapersonoversikt/service/azure/AzureADService.kt
Vi returnerer `emptyList()` i catch blokken ved feilende API kall. Da
håndterer cachen dette som gyldig output og den tomme listen er cachet
til senere. Vi ignorerer å cache tomme lister for å unngå dette
problemet.
=> Fix bug der error i ms graph API fyller cache med feil verdi

web/src/main/java/no/nav/modiapersonoversikt/service/saf/SafDokumentMapper.kt
For feilsøking ref manglende dokumenter. Dette viser oss om det er mange
dokumenter som filtres ut pga feil format og dermed ikke vises til
brukere.
=> Logg en warning når dokumenter fra saf filtres ut

web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt
Det er mulig at Tolk er satt, men med spraak er null. Da trengs det tolk
men man vet ikke hvilket språk. Dette håndteres ikke i dag.
=> Vis språk som ukjent dersom det ikke er satt

web/src/main/java/no/nav/modiapersonoversikt/service/skatteetaten/innkreving/Krav.kt
En oppdatering har gjort at swagger-doc ikke klarer å serialisere
LocalDate riktig. Den brukes kun her så vi overskriver den enkeltvis
foreløbig.
=> Eksplisitt sett format på LocalDate i OpenAPI doc

web/src/main/java/no/nav/modiapersonoversikt/rest/enhet/EnhetController.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/Persondata.kt, web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt, web/src/test/java/no/nav/modiapersonoversikt/LocalBeans.kt, web/src/test/java/no/nav/modiapersonoversikt/MainTest.kt
Springdoc tar kun utgangspunkt i navn på klasser ved schema generation,
som gjør at klasser med samme navn, men forskjellig innhold bare blir
generert en gang. Renamer Enhet i persondata slik at det kun er ett sted
Enhet blir brukt.
=> Fikse naming konflikt for Enhet

web/src/main/java/no/nav/modiapersonoversikt/rest/TilgangControllerV2.kt
Experiments kjører i ny tråd og authContext er threadLocal. Denne
funksjonen lager en wrapper med en kopi av authContext i threaden
eksperimentet kjører i
=> Fikse manglede authContext i experiment

proxy/src/main/resources/logback-stdout-fixed.xml
Viss eg tar rett no, så vil alle logger i proxyen gå til team log. Då er me sikre på at ingenting havnar i consolen,
=> Fjern team log marker filter på team log appender

web/src/main/java/no/nav/modiapersonoversikt/service/utbetaling/UtbetalingServiceImpl.kt
Reverts navikt/modiapersonoversikt-api#1667
Denne utgjorde ingenting fordi filtereringa skjer i utbetalingsapi
=> Revert "Filtrer utbetalingsdato på alle datoer"
